/* tslint:disable */
/* eslint-disable */
/**
 * Flixur API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorModel,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/ErrorModel';
import {
    type GreetingOutputBody,
    GreetingOutputBodyFromJSON,
    GreetingOutputBodyToJSON,
} from '../models/GreetingOutputBody';

export interface GetGreetingByNameRequest {
    name: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for getGreetingByName without sending the request
     */
    async getGreetingByNameRequestOpts(requestParameters: GetGreetingByNameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getGreetingByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/greeting/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get greeting by name
     */
    async getGreetingByNameRaw(requestParameters: GetGreetingByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GreetingOutputBody>> {
        const requestOptions = await this.getGreetingByNameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GreetingOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get greeting by name
     */
    async getGreetingByName(name: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GreetingOutputBody> {
        const response = await this.getGreetingByNameRaw({ name: name }, initOverrides);
        return await response.value();
    }

}
