/* tslint:disable */
/* eslint-disable */
/**
 * Flixur API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  GreetingOutputBody,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GreetingOutputBodyFromJSON,
    GreetingOutputBodyToJSON,
} from '../models/index';

export interface GetGreetingByNameRequest {
    name: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get greeting by name
     */
    async getGreetingByNameRaw(requestParameters: GetGreetingByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GreetingOutputBody>> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getGreetingByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/greeting/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GreetingOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get greeting by name
     */
    async getGreetingByName(requestParameters: GetGreetingByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GreetingOutputBody> {
        const response = await this.getGreetingByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
