/* tslint:disable */
/* eslint-disable */
/**
 * Flixur API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ArtistSearchOutputBody,
    ArtistSearchOutputBodyFromJSON,
    ArtistSearchOutputBodyToJSON,
} from '../models/ArtistSearchOutputBody';
import {
    type ArtistSearchRequest,
    ArtistSearchRequestFromJSON,
    ArtistSearchRequestToJSON,
} from '../models/ArtistSearchRequest';
import {
    type ErrorModel,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/ErrorModel';

export interface ArtistSearchOperationRequest {
    artistSearchRequest: Omit<ArtistSearchRequest, '$schema'>;
}

/**
 * 
 */
export class MusicApi extends runtime.BaseAPI {

    /**
     * Creates request options for artistSearch without sending the request
     */
    async artistSearchRequestOpts(requestParameters: ArtistSearchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['artistSearchRequest'] == null) {
            throw new runtime.RequiredError(
                'artistSearchRequest',
                'Required parameter "artistSearchRequest" was null or undefined when calling artistSearch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/music/artists/search`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ArtistSearchRequestToJSON(requestParameters['artistSearchRequest']),
        };
    }

    /**
     * Search for an artist by name.
     * Search for artists.
     */
    async artistSearchRaw(requestParameters: ArtistSearchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistSearchOutputBody>> {
        const requestOptions = await this.artistSearchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistSearchOutputBodyFromJSON(jsonValue));
    }

    /**
     * Search for an artist by name.
     * Search for artists.
     */
    async artistSearch(artistSearchRequest: ArtistSearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistSearchOutputBody> {
        const response = await this.artistSearchRaw({ artistSearchRequest: artistSearchRequest }, initOverrides);
        return await response.value();
    }

}
