/* tslint:disable */
/* eslint-disable */
/**
 * Flixur API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ArtistSearchOutputBody,
  ArtistSearchRequest,
  ErrorModel,
} from '../models/index';
import {
    ArtistSearchOutputBodyFromJSON,
    ArtistSearchOutputBodyToJSON,
    ArtistSearchRequestFromJSON,
    ArtistSearchRequestToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
} from '../models/index';

export interface ArtistSearchOperationRequest {
    artistSearchRequest: Omit<ArtistSearchRequest, '$schema'>;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Search for an artist by name.
     * Search for artists.
     */
    async artistSearchRaw(requestParameters: ArtistSearchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArtistSearchOutputBody>> {
        if (requestParameters['artistSearchRequest'] == null) {
            throw new runtime.RequiredError(
                'artistSearchRequest',
                'Required parameter "artistSearchRequest" was null or undefined when calling artistSearch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/music/artists/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ArtistSearchRequestToJSON(requestParameters['artistSearchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArtistSearchOutputBodyFromJSON(jsonValue));
    }

    /**
     * Search for an artist by name.
     * Search for artists.
     */
    async artistSearch(requestParameters: ArtistSearchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArtistSearchOutputBody> {
        const response = await this.artistSearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
