// CODE GENERATED BY GO:GENERATE
package api

const (
	CodeIncorrectPassword APIErrorCode = "INCORRECT_PASSWORD"
	CodeIncorrectUsername APIErrorCode = "INCORRECT_USERNAME"
	CodeTooLong           APIErrorCode = "TOO_LONG"
	CodeTooShort          APIErrorCode = "TOO_SHORT"
)

var APIErrorCodeStatusMap = map[APIErrorCode]int{
	CodeIncorrectPassword: 401,
	CodeIncorrectUsername: 401,
	CodeTooLong:           400,
	CodeTooShort:          400,
}

type APIErrorCodesMixin struct {
	Code APIErrorCode `json:"code" enum:"INCORRECT_PASSWORD,INCORRECT_USERNAME,TOO_LONG,TOO_SHORT"`
}
