// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"forge.xela.codes/xela/flixur/ent/predicate"
	"forge.xela.codes/xela/flixur/ent/usersession"
)

// UserSessionUpdate is the builder for updating UserSession entities.
type UserSessionUpdate struct {
	config
	hooks    []Hook
	mutation *UserSessionMutation
}

// Where appends a list predicates to the UserSessionUpdate builder.
func (_u *UserSessionUpdate) Where(ps ...predicate.UserSession) *UserSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *UserSessionUpdate) SetLastSeenAt(v time.Time) *UserSessionUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// Mutation returns the UserSessionMutation object of the builder.
func (_u *UserSessionUpdate) Mutation() *UserSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserSessionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSessionUpdate) defaults() error {
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		if usersession.UpdateDefaultLastSeenAt == nil {
			return fmt.Errorf("ent: uninitialized usersession.UpdateDefaultLastSeenAt (forgotten import ent/runtime?)")
		}
		v := usersession.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSessionUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSession.user"`)
	}
	return nil
}

func (_u *UserSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersession.Table, usersession.Columns, sqlgraph.NewFieldSpec(usersession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(usersession.FieldLastSeenAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserSessionUpdateOne is the builder for updating a single UserSession entity.
type UserSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSessionMutation
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *UserSessionUpdateOne) SetLastSeenAt(v time.Time) *UserSessionUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// Mutation returns the UserSessionMutation object of the builder.
func (_u *UserSessionUpdateOne) Mutation() *UserSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserSessionUpdate builder.
func (_u *UserSessionUpdateOne) Where(ps ...predicate.UserSession) *UserSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserSessionUpdateOne) Select(field string, fields ...string) *UserSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserSession entity.
func (_u *UserSessionUpdateOne) Save(ctx context.Context) (*UserSession, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSessionUpdateOne) SaveX(ctx context.Context) *UserSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSessionUpdateOne) defaults() error {
	if _, ok := _u.mutation.LastSeenAt(); !ok {
		if usersession.UpdateDefaultLastSeenAt == nil {
			return fmt.Errorf("ent: uninitialized usersession.UpdateDefaultLastSeenAt (forgotten import ent/runtime?)")
		}
		v := usersession.UpdateDefaultLastSeenAt()
		_u.mutation.SetLastSeenAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSessionUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSession.user"`)
	}
	return nil
}

func (_u *UserSessionUpdateOne) sqlSave(ctx context.Context) (_node *UserSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersession.Table, usersession.Columns, sqlgraph.NewFieldSpec(usersession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersession.FieldID)
		for _, f := range fields {
			if !usersession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(usersession.FieldLastSeenAt, field.TypeTime, value)
	}
	_node = &UserSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
