// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"forge.xela.codes/xela/flixur/ent/predicate"
	"forge.xela.codes/xela/flixur/ent/userlinkedoidc"
)

// UserLinkedOIDCUpdate is the builder for updating UserLinkedOIDC entities.
type UserLinkedOIDCUpdate struct {
	config
	hooks    []Hook
	mutation *UserLinkedOIDCMutation
}

// Where appends a list predicates to the UserLinkedOIDCUpdate builder.
func (_u *UserLinkedOIDCUpdate) Where(ps ...predicate.UserLinkedOIDC) *UserLinkedOIDCUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the UserLinkedOIDCMutation object of the builder.
func (_u *UserLinkedOIDCUpdate) Mutation() *UserLinkedOIDCMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserLinkedOIDCUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLinkedOIDCUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserLinkedOIDCUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLinkedOIDCUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserLinkedOIDCUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userlinkedoidc.Table, userlinkedoidc.Columns, sqlgraph.NewFieldSpec(userlinkedoidc.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlinkedoidc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserLinkedOIDCUpdateOne is the builder for updating a single UserLinkedOIDC entity.
type UserLinkedOIDCUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserLinkedOIDCMutation
}

// Mutation returns the UserLinkedOIDCMutation object of the builder.
func (_u *UserLinkedOIDCUpdateOne) Mutation() *UserLinkedOIDCMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserLinkedOIDCUpdate builder.
func (_u *UserLinkedOIDCUpdateOne) Where(ps ...predicate.UserLinkedOIDC) *UserLinkedOIDCUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserLinkedOIDCUpdateOne) Select(field string, fields ...string) *UserLinkedOIDCUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserLinkedOIDC entity.
func (_u *UserLinkedOIDCUpdateOne) Save(ctx context.Context) (*UserLinkedOIDC, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLinkedOIDCUpdateOne) SaveX(ctx context.Context) *UserLinkedOIDC {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserLinkedOIDCUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLinkedOIDCUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserLinkedOIDCUpdateOne) sqlSave(ctx context.Context) (_node *UserLinkedOIDC, err error) {
	_spec := sqlgraph.NewUpdateSpec(userlinkedoidc.Table, userlinkedoidc.Columns, sqlgraph.NewFieldSpec(userlinkedoidc.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserLinkedOIDC.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userlinkedoidc.FieldID)
		for _, f := range fields {
			if !userlinkedoidc.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userlinkedoidc.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &UserLinkedOIDC{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlinkedoidc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
