// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"forge.xela.codes/xela/flixur/ent/user"
	"forge.xela.codes/xela/flixur/ent/userlinkedoidc"
)

// UserLinkedOIDC is the model entity for the UserLinkedOIDC schema.
type UserLinkedOIDC struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Issuer URL for the OIDC provider.
	Issuer string `json:"issuer,omitempty"`
	// Subject returned from provider that identifies the user.
	Subject string `json:"subject,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserLinkedOIDCQuery when eager-loading is set.
	Edges           UserLinkedOIDCEdges `json:"edges"`
	user_oidc_links *string
	selectValues    sql.SelectValues
}

// UserLinkedOIDCEdges holds the relations/edges for other nodes in the graph.
type UserLinkedOIDCEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserLinkedOIDCEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserLinkedOIDC) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userlinkedoidc.FieldID:
			values[i] = new(sql.NullInt64)
		case userlinkedoidc.FieldIssuer, userlinkedoidc.FieldSubject:
			values[i] = new(sql.NullString)
		case userlinkedoidc.ForeignKeys[0]: // user_oidc_links
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserLinkedOIDC fields.
func (_m *UserLinkedOIDC) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userlinkedoidc.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userlinkedoidc.FieldIssuer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issuer", values[i])
			} else if value.Valid {
				_m.Issuer = value.String
			}
		case userlinkedoidc.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case userlinkedoidc.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_oidc_links", values[i])
			} else if value.Valid {
				_m.user_oidc_links = new(string)
				*_m.user_oidc_links = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserLinkedOIDC.
// This includes values selected through modifiers, order, etc.
func (_m *UserLinkedOIDC) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserLinkedOIDC entity.
func (_m *UserLinkedOIDC) QueryUser() *UserQuery {
	return NewUserLinkedOIDCClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserLinkedOIDC.
// Note that you need to call UserLinkedOIDC.Unwrap() before calling this method if this UserLinkedOIDC
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserLinkedOIDC) Update() *UserLinkedOIDCUpdateOne {
	return NewUserLinkedOIDCClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserLinkedOIDC entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserLinkedOIDC) Unwrap() *UserLinkedOIDC {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserLinkedOIDC is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserLinkedOIDC) String() string {
	var builder strings.Builder
	builder.WriteString("UserLinkedOIDC(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("issuer=")
	builder.WriteString(_m.Issuer)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteByte(')')
	return builder.String()
}

// UserLinkedOIDCs is a parsable slice of UserLinkedOIDC.
type UserLinkedOIDCs []*UserLinkedOIDC
