// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"forge.xela.codes/xela/flixur/ent/predicate"
	"forge.xela.codes/xela/flixur/ent/user"
	"forge.xela.codes/xela/flixur/ent/userlinkedoidc"
)

// UserLinkedOIDCUpdate is the builder for updating UserLinkedOIDC entities.
type UserLinkedOIDCUpdate struct {
	config
	hooks    []Hook
	mutation *UserLinkedOIDCMutation
}

// Where appends a list predicates to the UserLinkedOIDCUpdate builder.
func (_u *UserLinkedOIDCUpdate) Where(ps ...predicate.UserLinkedOIDC) *UserLinkedOIDCUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *UserLinkedOIDCUpdate) SetIssuer(v string) *UserLinkedOIDCUpdate {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *UserLinkedOIDCUpdate) SetNillableIssuer(v *string) *UserLinkedOIDCUpdate {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *UserLinkedOIDCUpdate) SetSubject(v string) *UserLinkedOIDCUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *UserLinkedOIDCUpdate) SetNillableSubject(v *string) *UserLinkedOIDCUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserLinkedOIDCUpdate) SetUserID(id string) *UserLinkedOIDCUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserLinkedOIDCUpdate) SetUser(v *User) *UserLinkedOIDCUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserLinkedOIDCMutation object of the builder.
func (_u *UserLinkedOIDCUpdate) Mutation() *UserLinkedOIDCMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserLinkedOIDCUpdate) ClearUser() *UserLinkedOIDCUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserLinkedOIDCUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLinkedOIDCUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserLinkedOIDCUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLinkedOIDCUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserLinkedOIDCUpdate) check() error {
	if v, ok := _u.mutation.Issuer(); ok {
		if err := userlinkedoidc.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "UserLinkedOIDC.issuer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := userlinkedoidc.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "UserLinkedOIDC.subject": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserLinkedOIDC.user"`)
	}
	return nil
}

func (_u *UserLinkedOIDCUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userlinkedoidc.Table, userlinkedoidc.Columns, sqlgraph.NewFieldSpec(userlinkedoidc.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(userlinkedoidc.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(userlinkedoidc.FieldSubject, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlinkedoidc.UserTable,
			Columns: []string{userlinkedoidc.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlinkedoidc.UserTable,
			Columns: []string{userlinkedoidc.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlinkedoidc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserLinkedOIDCUpdateOne is the builder for updating a single UserLinkedOIDC entity.
type UserLinkedOIDCUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserLinkedOIDCMutation
}

// SetIssuer sets the "issuer" field.
func (_u *UserLinkedOIDCUpdateOne) SetIssuer(v string) *UserLinkedOIDCUpdateOne {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *UserLinkedOIDCUpdateOne) SetNillableIssuer(v *string) *UserLinkedOIDCUpdateOne {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *UserLinkedOIDCUpdateOne) SetSubject(v string) *UserLinkedOIDCUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *UserLinkedOIDCUpdateOne) SetNillableSubject(v *string) *UserLinkedOIDCUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *UserLinkedOIDCUpdateOne) SetUserID(id string) *UserLinkedOIDCUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserLinkedOIDCUpdateOne) SetUser(v *User) *UserLinkedOIDCUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserLinkedOIDCMutation object of the builder.
func (_u *UserLinkedOIDCUpdateOne) Mutation() *UserLinkedOIDCMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserLinkedOIDCUpdateOne) ClearUser() *UserLinkedOIDCUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserLinkedOIDCUpdate builder.
func (_u *UserLinkedOIDCUpdateOne) Where(ps ...predicate.UserLinkedOIDC) *UserLinkedOIDCUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserLinkedOIDCUpdateOne) Select(field string, fields ...string) *UserLinkedOIDCUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserLinkedOIDC entity.
func (_u *UserLinkedOIDCUpdateOne) Save(ctx context.Context) (*UserLinkedOIDC, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserLinkedOIDCUpdateOne) SaveX(ctx context.Context) *UserLinkedOIDC {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserLinkedOIDCUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserLinkedOIDCUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserLinkedOIDCUpdateOne) check() error {
	if v, ok := _u.mutation.Issuer(); ok {
		if err := userlinkedoidc.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "UserLinkedOIDC.issuer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := userlinkedoidc.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "UserLinkedOIDC.subject": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserLinkedOIDC.user"`)
	}
	return nil
}

func (_u *UserLinkedOIDCUpdateOne) sqlSave(ctx context.Context) (_node *UserLinkedOIDC, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userlinkedoidc.Table, userlinkedoidc.Columns, sqlgraph.NewFieldSpec(userlinkedoidc.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserLinkedOIDC.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userlinkedoidc.FieldID)
		for _, f := range fields {
			if !userlinkedoidc.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userlinkedoidc.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(userlinkedoidc.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(userlinkedoidc.FieldSubject, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlinkedoidc.UserTable,
			Columns: []string{userlinkedoidc.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlinkedoidc.UserTable,
			Columns: []string{userlinkedoidc.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserLinkedOIDC{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userlinkedoidc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
