// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"forge.xela.codes/xela/flixur/ent/user"
	"forge.xela.codes/xela/flixur/ent/userlinkedoidc"
)

// UserLinkedOIDCCreate is the builder for creating a UserLinkedOIDC entity.
type UserLinkedOIDCCreate struct {
	config
	mutation *UserLinkedOIDCMutation
	hooks    []Hook
}

// SetIssuer sets the "issuer" field.
func (_c *UserLinkedOIDCCreate) SetIssuer(v string) *UserLinkedOIDCCreate {
	_c.mutation.SetIssuer(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *UserLinkedOIDCCreate) SetSubject(v string) *UserLinkedOIDCCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *UserLinkedOIDCCreate) SetUserID(id string) *UserLinkedOIDCCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserLinkedOIDCCreate) SetUser(v *User) *UserLinkedOIDCCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserLinkedOIDCMutation object of the builder.
func (_c *UserLinkedOIDCCreate) Mutation() *UserLinkedOIDCMutation {
	return _c.mutation
}

// Save creates the UserLinkedOIDC in the database.
func (_c *UserLinkedOIDCCreate) Save(ctx context.Context) (*UserLinkedOIDC, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserLinkedOIDCCreate) SaveX(ctx context.Context) *UserLinkedOIDC {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLinkedOIDCCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLinkedOIDCCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserLinkedOIDCCreate) check() error {
	if _, ok := _c.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "UserLinkedOIDC.issuer"`)}
	}
	if v, ok := _c.mutation.Issuer(); ok {
		if err := userlinkedoidc.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "UserLinkedOIDC.issuer": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "UserLinkedOIDC.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := userlinkedoidc.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "UserLinkedOIDC.subject": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserLinkedOIDC.user"`)}
	}
	return nil
}

func (_c *UserLinkedOIDCCreate) sqlSave(ctx context.Context) (*UserLinkedOIDC, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserLinkedOIDCCreate) createSpec() (*UserLinkedOIDC, *sqlgraph.CreateSpec) {
	var (
		_node = &UserLinkedOIDC{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userlinkedoidc.Table, sqlgraph.NewFieldSpec(userlinkedoidc.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Issuer(); ok {
		_spec.SetField(userlinkedoidc.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(userlinkedoidc.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userlinkedoidc.UserTable,
			Columns: []string{userlinkedoidc.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_oidc_links = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserLinkedOIDCCreateBulk is the builder for creating many UserLinkedOIDC entities in bulk.
type UserLinkedOIDCCreateBulk struct {
	config
	err      error
	builders []*UserLinkedOIDCCreate
}

// Save creates the UserLinkedOIDC entities in the database.
func (_c *UserLinkedOIDCCreateBulk) Save(ctx context.Context) ([]*UserLinkedOIDC, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserLinkedOIDC, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserLinkedOIDCMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserLinkedOIDCCreateBulk) SaveX(ctx context.Context) []*UserLinkedOIDC {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserLinkedOIDCCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserLinkedOIDCCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
