// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserLinkedOIDC is the predicate function for userlinkedoidc builders.
type UserLinkedOIDC func(*sql.Selector)

// UserSession is the predicate function for usersession builders.
type UserSession func(*sql.Selector)
