/* tslint:disable */
/* eslint-disable */
/**
 * Flixur API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArtistSearchRequest
 */
export interface ArtistSearchRequest {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ArtistSearchRequest
     */
    readonly $schema?: string;
    /**
     * 
     * @type {number}
     * @memberof ArtistSearchRequest
     */
    limit?: number;
    /**
     * Plugin ID to use for the request. Omit to use the local server.
     * @type {string}
     * @memberof ArtistSearchRequest
     */
    plugin?: string;
    /**
     * 
     * @type {string}
     * @memberof ArtistSearchRequest
     */
    query: string;
}

/**
 * Check if a given object implements the ArtistSearchRequest interface.
 */
export function instanceOfArtistSearchRequest(value: object): value is ArtistSearchRequest {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function ArtistSearchRequestFromJSON(json: any): ArtistSearchRequest {
    return ArtistSearchRequestFromJSONTyped(json, false);
}

export function ArtistSearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistSearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'plugin': json['plugin'] == null ? undefined : json['plugin'],
        'query': json['query'],
    };
}

export function ArtistSearchRequestToJSON(json: any): ArtistSearchRequest {
    return ArtistSearchRequestToJSONTyped(json, false);
}

export function ArtistSearchRequestToJSONTyped(value?: Omit<ArtistSearchRequest, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'plugin': value['plugin'],
        'query': value['query'],
    };
}

