/* tslint:disable */
/* eslint-disable */
/**
 * Flixur API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Artist
 */
export interface Artist {
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Artist
     */
    followers?: number;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Artist
     */
    provider: string;
}

/**
 * Check if a given object implements the Artist interface.
 */
export function instanceOfArtist(value: object): value is Artist {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function ArtistFromJSON(json: any): Artist {
    return ArtistFromJSONTyped(json, false);
}

export function ArtistFromJSONTyped(json: any, ignoreDiscriminator: boolean): Artist {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'followers': json['followers'] == null ? undefined : json['followers'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'id': json['id'],
        'location': json['location'] == null ? undefined : json['location'],
        'name': json['name'],
        'provider': json['provider'],
    };
}

export function ArtistToJSON(json: any): Artist {
    return ArtistToJSONTyped(json, false);
}

export function ArtistToJSONTyped(value?: Artist | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'followers': value['followers'],
        'icon': value['icon'],
        'id': value['id'],
        'location': value['location'],
        'name': value['name'],
        'provider': value['provider'],
    };
}

