/* tslint:disable */
/* eslint-disable */
/**
 * Flixur API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Artist } from './Artist';
import {
    ArtistFromJSON,
    ArtistFromJSONTyped,
    ArtistToJSON,
    ArtistToJSONTyped,
} from './Artist';

/**
 * 
 * @export
 * @interface ArtistSearchOutputBody
 */
export interface ArtistSearchOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof ArtistSearchOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Array<Artist>}
     * @memberof ArtistSearchOutputBody
     */
    list: Array<Artist> | null;
}

/**
 * Check if a given object implements the ArtistSearchOutputBody interface.
 */
export function instanceOfArtistSearchOutputBody(value: object): value is ArtistSearchOutputBody {
    if (!('list' in value) || value['list'] === undefined) return false;
    return true;
}

export function ArtistSearchOutputBodyFromJSON(json: any): ArtistSearchOutputBody {
    return ArtistSearchOutputBodyFromJSONTyped(json, false);
}

export function ArtistSearchOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtistSearchOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'list': (json['list'] == null ? null : (json['list'] as Array<any>).map(ArtistFromJSON)),
    };
}

export function ArtistSearchOutputBodyToJSON(json: any): ArtistSearchOutputBody {
    return ArtistSearchOutputBodyToJSONTyped(json, false);
}

export function ArtistSearchOutputBodyToJSONTyped(value?: Omit<ArtistSearchOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list': (value['list'] == null ? null : (value['list'] as Array<any>).map(ArtistToJSON)),
    };
}

