/* tslint:disable */
/* eslint-disable */
/**
 * Flixur API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GreetingOutputBody
 */
export interface GreetingOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GreetingOutputBody
     */
    readonly $schema?: string;
    /**
     * Greeting message
     * @type {string}
     * @memberof GreetingOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the GreetingOutputBody interface.
 */
export function instanceOfGreetingOutputBody(value: object): value is GreetingOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GreetingOutputBodyFromJSON(json: any): GreetingOutputBody {
    return GreetingOutputBodyFromJSONTyped(json, false);
}

export function GreetingOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GreetingOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
    };
}

export function GreetingOutputBodyToJSON(json: any): GreetingOutputBody {
    return GreetingOutputBodyToJSONTyped(json, false);
}

export function GreetingOutputBodyToJSONTyped(value?: Omit<GreetingOutputBody, '$schema'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

