package main

import (
	"bytes"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"strings"
)

type errCode struct {
	name   string
	status int
}

// list of error codes to generate from
// ! keep this sorted
//
//go:generate go run .
var errorCodeList = []errCode{
	{"INCORRECT_PASSWORD", http.StatusUnauthorized},
	{"INCORRECT_USERNAME", http.StatusUnauthorized},
	{"TOO_LONG", http.StatusBadRequest},
	{"TOO_SHORT", http.StatusBadRequest},
}

// converts a SCREAMING_CASE string to PascalCase
func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
	}
	return strings.Join(parts, "")
}

func main() {
	var b bytes.Buffer
	b.WriteString("// CODE GENERATED BY GO:GENERATE\n")
	b.WriteString("package api\n\nconst (\n")
	for _, c := range errorCodeList {
		fmt.Fprintf(&b, "\tCode%s APIErrorCode = %q\n", toPascalCase(c.name), c.name)
	}
	b.WriteString(")\n\n")

	b.WriteString("var APIErrorCodeStatusMap = map[APIErrorCode]int{\n")
	for _, c := range errorCodeList {
		fmt.Fprintf(&b, "\tCode%s: %d,\n", toPascalCase(c.name), c.status)
	}
	b.WriteString("}\n\n")

	b.WriteString(`type APIErrorCodesMixin struct {
	Code   APIErrorCode   ` + "`json:\"code\" enum:\"")
	for i, c := range errorCodeList {
		if i != 0 {
			b.WriteString(",")
		}
		b.WriteString(c.name)
	}
	b.WriteString("\"`\n}")

	src, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("../errors_gen.go", src, 0644); err != nil {
		panic(err)
	}
}
