// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "password", Type: field.TypeString},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "permissions", Type: field.TypeJSON},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserLinkedOidCsColumns holds the columns for the "user_linked_oid_cs" table.
	UserLinkedOidCsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "issuer", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "user_oidc_links", Type: field.TypeString},
	}
	// UserLinkedOidCsTable holds the schema information for the "user_linked_oid_cs" table.
	UserLinkedOidCsTable = &schema.Table{
		Name:       "user_linked_oid_cs",
		Columns:    UserLinkedOidCsColumns,
		PrimaryKey: []*schema.Column{UserLinkedOidCsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_linked_oid_cs_users_oidcLinks",
				Columns:    []*schema.Column{UserLinkedOidCsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userlinkedoidc_issuer_subject",
				Unique:  true,
				Columns: []*schema.Column{UserLinkedOidCsColumns[1], UserLinkedOidCsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		UserLinkedOidCsTable,
	}
)

func init() {
	UserLinkedOidCsTable.ForeignKeys[0].RefTable = UsersTable
}
