// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in forge.xela.codes/xela/flixur/ent/runtime.go

const (
	Version = "0.14.6"                                              // Version of ent codegen.
	Sum     = "sha256-pkD8MYyinvuKCtSpHGfFE9y8GRP40qdeyjhB32yeiK4=" // Sum of ent codegen.
)
