// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"forge.xela.codes/xela/flixur/ent/schema"
	"forge.xela.codes/xela/flixur/ent/user"
	"forge.xela.codes/xela/flixur/ent/userlinkedoidc"
	"forge.xela.codes/xela/flixur/ent/usersession"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userMixin := schema.User{}.Mixin()
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[2].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescPermissions is the schema descriptor for permissions field.
	userDescPermissions := userFields[3].Descriptor()
	// user.DefaultPermissions holds the default value on creation for the permissions field.
	user.DefaultPermissions = userDescPermissions.Default.([]string)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
	userlinkedoidcFields := schema.UserLinkedOIDC{}.Fields()
	_ = userlinkedoidcFields
	// userlinkedoidcDescIssuer is the schema descriptor for issuer field.
	userlinkedoidcDescIssuer := userlinkedoidcFields[0].Descriptor()
	// userlinkedoidc.IssuerValidator is a validator for the "issuer" field. It is called by the builders before save.
	userlinkedoidc.IssuerValidator = userlinkedoidcDescIssuer.Validators[0].(func(string) error)
	// userlinkedoidcDescSubject is the schema descriptor for subject field.
	userlinkedoidcDescSubject := userlinkedoidcFields[1].Descriptor()
	// userlinkedoidc.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	userlinkedoidc.SubjectValidator = userlinkedoidcDescSubject.Validators[0].(func(string) error)
	usersessionMixin := schema.UserSession{}.Mixin()
	usersessionMixinFields0 := usersessionMixin[0].Fields()
	_ = usersessionMixinFields0
	usersessionFields := schema.UserSession{}.Fields()
	_ = usersessionFields
	// usersessionDescIPAddress is the schema descriptor for ip_address field.
	usersessionDescIPAddress := usersessionFields[0].Descriptor()
	// usersession.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	usersession.IPAddressValidator = usersessionDescIPAddress.Validators[0].(func(string) error)
	// usersessionDescCreatedAt is the schema descriptor for created_at field.
	usersessionDescCreatedAt := usersessionFields[2].Descriptor()
	// usersession.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersession.DefaultCreatedAt = usersessionDescCreatedAt.Default.(func() time.Time)
	// usersessionDescLastSeenAt is the schema descriptor for last_seen_at field.
	usersessionDescLastSeenAt := usersessionFields[3].Descriptor()
	// usersession.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	usersession.DefaultLastSeenAt = usersessionDescLastSeenAt.Default.(func() time.Time)
	// usersession.UpdateDefaultLastSeenAt holds the default value on update for the last_seen_at field.
	usersession.UpdateDefaultLastSeenAt = usersessionDescLastSeenAt.UpdateDefault.(func() time.Time)
	// usersessionDescID is the schema descriptor for id field.
	usersessionDescID := usersessionMixinFields0[0].Descriptor()
	// usersession.DefaultID holds the default value on creation for the id field.
	usersession.DefaultID = usersessionDescID.Default.(func() string)
}

const (
	Version = "0.14.6"                                              // Version of ent codegen.
	Sum     = "sha256-pkD8MYyinvuKCtSpHGfFE9y8GRP40qdeyjhB32yeiK4=" // Sum of ent codegen.
)
