// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: features.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error response from any feature.
type FeatureError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

func (x *FeatureError) Reset() {
	*x = FeatureError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureError) ProtoMessage() {}

func (x *FeatureError) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureError.ProtoReflect.Descriptor instead.
func (*FeatureError) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FeatureError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get a specific artist by ID.
type FeatureArtistGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
}

func (x *FeatureArtistGetRequest) Reset() {
	*x = FeatureArtistGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureArtistGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureArtistGetRequest) ProtoMessage() {}

func (x *FeatureArtistGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureArtistGetRequest.ProtoReflect.Descriptor instead.
func (*FeatureArtistGetRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureArtistGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FeatureArtistGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist *Artist `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
}

func (x *FeatureArtistGetResponse) Reset() {
	*x = FeatureArtistGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureArtistGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureArtistGetResponse) ProtoMessage() {}

func (x *FeatureArtistGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureArtistGetResponse.ProtoReflect.Descriptor instead.
func (*FeatureArtistGetResponse) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureArtistGetResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

// Search for an artist by name.
type FeatureArtistSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query"`
}

func (x *FeatureArtistSearchRequest) Reset() {
	*x = FeatureArtistSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureArtistSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureArtistSearchRequest) ProtoMessage() {}

func (x *FeatureArtistSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureArtistSearchRequest.ProtoReflect.Descriptor instead.
func (*FeatureArtistSearchRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{3}
}

func (x *FeatureArtistSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type FeatureArtistSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*Artist `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *FeatureArtistSearchResponse) Reset() {
	*x = FeatureArtistSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_features_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureArtistSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureArtistSearchResponse) ProtoMessage() {}

func (x *FeatureArtistSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureArtistSearchResponse.ProtoReflect.Descriptor instead.
func (*FeatureArtistSearchResponse) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{4}
}

func (x *FeatureArtistSearchResponse) GetResults() []*Artist {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_features_proto protoreflect.FileDescriptor

var file_features_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x1a, 0x0b, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c,
	0x0a, 0x0c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x17,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x18, 0x46, 0x65, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x2e, 0x6d, 0x75, 0x73,
	0x69, 0x63, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x22, 0x32, 0x0a, 0x1a, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x4d, 0x0a, 0x1b, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x2e, 0x6d,
	0x75, 0x73, 0x69, 0x63, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x61, 0x70, 0x70, 0x2f, 0x66, 0x6c, 0x69,
	0x78, 0x75, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_features_proto_rawDescOnce sync.Once
	file_features_proto_rawDescData = file_features_proto_rawDesc
)

func file_features_proto_rawDescGZIP() []byte {
	file_features_proto_rawDescOnce.Do(func() {
		file_features_proto_rawDescData = protoimpl.X.CompressGZIP(file_features_proto_rawDescData)
	})
	return file_features_proto_rawDescData
}

var file_features_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_features_proto_goTypes = []interface{}{
	(*FeatureError)(nil),                // 0: flixur.features.FeatureError
	(*FeatureArtistGetRequest)(nil),     // 1: flixur.features.FeatureArtistGetRequest
	(*FeatureArtistGetResponse)(nil),    // 2: flixur.features.FeatureArtistGetResponse
	(*FeatureArtistSearchRequest)(nil),  // 3: flixur.features.FeatureArtistSearchRequest
	(*FeatureArtistSearchResponse)(nil), // 4: flixur.features.FeatureArtistSearchResponse
	(*Artist)(nil),                      // 5: flixur.music.Artist
}
var file_features_proto_depIdxs = []int32{
	5, // 0: flixur.features.FeatureArtistGetResponse.artist:type_name -> flixur.music.Artist
	5, // 1: flixur.features.FeatureArtistSearchResponse.results:type_name -> flixur.music.Artist
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_features_proto_init() }
func file_features_proto_init() {
	if File_features_proto != nil {
		return
	}
	file_music_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_features_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureArtistGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureArtistGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureArtistSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_features_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureArtistSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_features_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_features_proto_goTypes,
		DependencyIndexes: file_features_proto_depIdxs,
		MessageInfos:      file_features_proto_msgTypes,
	}.Build()
	File_features_proto = out.File
	file_features_proto_rawDesc = nil
	file_features_proto_goTypes = nil
	file_features_proto_depIdxs = nil
}
