// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: features.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureErrorCode int32

const (
	FeatureErrorCode_UNKNOWN         FeatureErrorCode = 0
	FeatureErrorCode_NOT_INITIALIZED FeatureErrorCode = 1
	FeatureErrorCode_NOT_FOUND       FeatureErrorCode = 2
	FeatureErrorCode_RATELIMITED     FeatureErrorCode = 3
)

// Enum value maps for FeatureErrorCode.
var (
	FeatureErrorCode_name = map[int32]string{
		0: "UNKNOWN",
		1: "NOT_INITIALIZED",
		2: "NOT_FOUND",
		3: "RATELIMITED",
	}
	FeatureErrorCode_value = map[string]int32{
		"UNKNOWN":         0,
		"NOT_INITIALIZED": 1,
		"NOT_FOUND":       2,
		"RATELIMITED":     3,
	}
)

func (x FeatureErrorCode) Enum() *FeatureErrorCode {
	p := new(FeatureErrorCode)
	*p = x
	return p
}

func (x FeatureErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeatureErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_features_proto_enumTypes[0].Descriptor()
}

func (FeatureErrorCode) Type() protoreflect.EnumType {
	return &file_features_proto_enumTypes[0]
}

func (x FeatureErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeatureErrorCode.Descriptor instead.
func (FeatureErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{0}
}

// Error response from any feature.
type FeatureError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureError) Reset() {
	*x = FeatureError{}
	mi := &file_features_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureError) ProtoMessage() {}

func (x *FeatureError) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureError.ProtoReflect.Descriptor instead.
func (*FeatureError) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FeatureError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get a specific artist by ID.
type FeatureArtistGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureArtistGetRequest) Reset() {
	*x = FeatureArtistGetRequest{}
	mi := &file_features_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureArtistGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureArtistGetRequest) ProtoMessage() {}

func (x *FeatureArtistGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureArtistGetRequest.ProtoReflect.Descriptor instead.
func (*FeatureArtistGetRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureArtistGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FeatureArtistGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *Artist                `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureArtistGetResponse) Reset() {
	*x = FeatureArtistGetResponse{}
	mi := &file_features_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureArtistGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureArtistGetResponse) ProtoMessage() {}

func (x *FeatureArtistGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureArtistGetResponse.ProtoReflect.Descriptor instead.
func (*FeatureArtistGetResponse) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureArtistGetResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

// Search for an artist by name.
type FeatureArtistSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query"`
	// Limit of items to fetch. Will be clamped to max request size limit if applicable.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureArtistSearchRequest) Reset() {
	*x = FeatureArtistSearchRequest{}
	mi := &file_features_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureArtistSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureArtistSearchRequest) ProtoMessage() {}

func (x *FeatureArtistSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureArtistSearchRequest.ProtoReflect.Descriptor instead.
func (*FeatureArtistSearchRequest) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{3}
}

func (x *FeatureArtistSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *FeatureArtistSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FeatureArtistSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Artist              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureArtistSearchResponse) Reset() {
	*x = FeatureArtistSearchResponse{}
	mi := &file_features_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureArtistSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureArtistSearchResponse) ProtoMessage() {}

func (x *FeatureArtistSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_features_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureArtistSearchResponse.ProtoReflect.Descriptor instead.
func (*FeatureArtistSearchResponse) Descriptor() ([]byte, []int) {
	return file_features_proto_rawDescGZIP(), []int{4}
}

func (x *FeatureArtistSearchResponse) GetResults() []*Artist {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_features_proto protoreflect.FileDescriptor

const file_features_proto_rawDesc = "" +
	"\n" +
	"\x0efeatures.proto\x12\x0fflixur.features\x1a\vmusic.proto\"<\n" +
	"\fFeatureError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x17FeatureArtistGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x18FeatureArtistGetResponse\x12,\n" +
	"\x06artist\x18\x01 \x01(\v2\x14.flixur.music.ArtistR\x06artist\"H\n" +
	"\x1aFeatureArtistSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"M\n" +
	"\x1bFeatureArtistSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.flixur.music.ArtistR\aresults*T\n" +
	"\x10FeatureErrorCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fNOT_INITIALIZED\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\x0f\n" +
	"\vRATELIMITED\x10\x03B&Z$github.com/flixurapp/flixur/proto/gob\x06proto3"

var (
	file_features_proto_rawDescOnce sync.Once
	file_features_proto_rawDescData []byte
)

func file_features_proto_rawDescGZIP() []byte {
	file_features_proto_rawDescOnce.Do(func() {
		file_features_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_features_proto_rawDesc), len(file_features_proto_rawDesc)))
	})
	return file_features_proto_rawDescData
}

var file_features_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_features_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_features_proto_goTypes = []any{
	(FeatureErrorCode)(0),               // 0: flixur.features.FeatureErrorCode
	(*FeatureError)(nil),                // 1: flixur.features.FeatureError
	(*FeatureArtistGetRequest)(nil),     // 2: flixur.features.FeatureArtistGetRequest
	(*FeatureArtistGetResponse)(nil),    // 3: flixur.features.FeatureArtistGetResponse
	(*FeatureArtistSearchRequest)(nil),  // 4: flixur.features.FeatureArtistSearchRequest
	(*FeatureArtistSearchResponse)(nil), // 5: flixur.features.FeatureArtistSearchResponse
	(*Artist)(nil),                      // 6: flixur.music.Artist
}
var file_features_proto_depIdxs = []int32{
	6, // 0: flixur.features.FeatureArtistGetResponse.artist:type_name -> flixur.music.Artist
	6, // 1: flixur.features.FeatureArtistSearchResponse.results:type_name -> flixur.music.Artist
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_features_proto_init() }
func file_features_proto_init() {
	if File_features_proto != nil {
		return
	}
	file_music_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_features_proto_rawDesc), len(file_features_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_features_proto_goTypes,
		DependencyIndexes: file_features_proto_depIdxs,
		EnumInfos:         file_features_proto_enumTypes,
		MessageInfos:      file_features_proto_msgTypes,
	}.Build()
	File_features_proto = out.File
	file_features_proto_goTypes = nil
	file_features_proto_depIdxs = nil
}
