// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: music_features.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetArtist
type ArtistGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistGetRequest) Reset() {
	*x = ArtistGetRequest{}
	mi := &file_music_features_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistGetRequest) ProtoMessage() {}

func (x *ArtistGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistGetRequest.ProtoReflect.Descriptor instead.
func (*ArtistGetRequest) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{0}
}

func (x *ArtistGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArtistGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artist        *Artist                `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistGetResponse) Reset() {
	*x = ArtistGetResponse{}
	mi := &file_music_features_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistGetResponse) ProtoMessage() {}

func (x *ArtistGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistGetResponse.ProtoReflect.Descriptor instead.
func (*ArtistGetResponse) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{1}
}

func (x *ArtistGetResponse) GetArtist() *Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

// SearchArtists
type ArtistSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query"`
	// Limit of items to fetch. Will be clamped to max request size limit if applicable.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistSearchRequest) Reset() {
	*x = ArtistSearchRequest{}
	mi := &file_music_features_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistSearchRequest) ProtoMessage() {}

func (x *ArtistSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistSearchRequest.ProtoReflect.Descriptor instead.
func (*ArtistSearchRequest) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{2}
}

func (x *ArtistSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ArtistSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ArtistSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Artist              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistSearchResponse) Reset() {
	*x = ArtistSearchResponse{}
	mi := &file_music_features_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistSearchResponse) ProtoMessage() {}

func (x *ArtistSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistSearchResponse.ProtoReflect.Descriptor instead.
func (*ArtistSearchResponse) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{3}
}

func (x *ArtistSearchResponse) GetResults() []*Artist {
	if x != nil {
		return x.Results
	}
	return nil
}

// GetAlbum
type AlbumGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumGetRequest) Reset() {
	*x = AlbumGetRequest{}
	mi := &file_music_features_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumGetRequest) ProtoMessage() {}

func (x *AlbumGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumGetRequest.ProtoReflect.Descriptor instead.
func (*AlbumGetRequest) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{4}
}

func (x *AlbumGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AlbumGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumGetResponse) Reset() {
	*x = AlbumGetResponse{}
	mi := &file_music_features_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumGetResponse) ProtoMessage() {}

func (x *AlbumGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumGetResponse.ProtoReflect.Descriptor instead.
func (*AlbumGetResponse) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{5}
}

func (x *AlbumGetResponse) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

// SearchAlbums
type AlbumSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query"`
	// Limit of items to fetch. Will be clamped to max request size limit if applicable.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumSearchRequest) Reset() {
	*x = AlbumSearchRequest{}
	mi := &file_music_features_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumSearchRequest) ProtoMessage() {}

func (x *AlbumSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumSearchRequest.ProtoReflect.Descriptor instead.
func (*AlbumSearchRequest) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{6}
}

func (x *AlbumSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AlbumSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AlbumSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Album               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumSearchResponse) Reset() {
	*x = AlbumSearchResponse{}
	mi := &file_music_features_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumSearchResponse) ProtoMessage() {}

func (x *AlbumSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumSearchResponse.ProtoReflect.Descriptor instead.
func (*AlbumSearchResponse) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{7}
}

func (x *AlbumSearchResponse) GetResults() []*Album {
	if x != nil {
		return x.Results
	}
	return nil
}

// GetTrack
type TrackGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackGetRequest) Reset() {
	*x = TrackGetRequest{}
	mi := &file_music_features_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackGetRequest) ProtoMessage() {}

func (x *TrackGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackGetRequest.ProtoReflect.Descriptor instead.
func (*TrackGetRequest) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{8}
}

func (x *TrackGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TrackGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *Track                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackGetResponse) Reset() {
	*x = TrackGetResponse{}
	mi := &file_music_features_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackGetResponse) ProtoMessage() {}

func (x *TrackGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackGetResponse.ProtoReflect.Descriptor instead.
func (*TrackGetResponse) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{9}
}

func (x *TrackGetResponse) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

// SearchTracks
type TrackSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query"`
	// Limit of items to fetch. Will be clamped to max request size limit if applicable.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackSearchRequest) Reset() {
	*x = TrackSearchRequest{}
	mi := &file_music_features_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackSearchRequest) ProtoMessage() {}

func (x *TrackSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackSearchRequest.ProtoReflect.Descriptor instead.
func (*TrackSearchRequest) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{10}
}

func (x *TrackSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TrackSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TrackSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Track               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackSearchResponse) Reset() {
	*x = TrackSearchResponse{}
	mi := &file_music_features_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackSearchResponse) ProtoMessage() {}

func (x *TrackSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_music_features_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackSearchResponse.ProtoReflect.Descriptor instead.
func (*TrackSearchResponse) Descriptor() ([]byte, []int) {
	return file_music_features_proto_rawDescGZIP(), []int{11}
}

func (x *TrackSearchResponse) GetResults() []*Track {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_music_features_proto protoreflect.FileDescriptor

const file_music_features_proto_rawDesc = "" +
	"\n" +
	"\x14music_features.proto\x12\x15flixur.music_features\x1a\vmusic.proto\"\"\n" +
	"\x10ArtistGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x11ArtistGetResponse\x12,\n" +
	"\x06artist\x18\x01 \x01(\v2\x14.flixur.music.ArtistR\x06artist\"A\n" +
	"\x13ArtistSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"F\n" +
	"\x14ArtistSearchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.flixur.music.ArtistR\aresults\"!\n" +
	"\x0fAlbumGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x10AlbumGetResponse\x12)\n" +
	"\x05album\x18\x01 \x01(\v2\x13.flixur.music.AlbumR\x05album\"@\n" +
	"\x12AlbumSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"D\n" +
	"\x13AlbumSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.flixur.music.AlbumR\aresults\"!\n" +
	"\x0fTrackGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x10TrackGetResponse\x12)\n" +
	"\x05track\x18\x01 \x01(\v2\x13.flixur.music.TrackR\x05track\"@\n" +
	"\x12TrackSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"D\n" +
	"\x13TrackSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.flixur.music.TrackR\aresultsB&Z$github.com/flixurapp/flixur/proto/gob\x06proto3"

var (
	file_music_features_proto_rawDescOnce sync.Once
	file_music_features_proto_rawDescData []byte
)

func file_music_features_proto_rawDescGZIP() []byte {
	file_music_features_proto_rawDescOnce.Do(func() {
		file_music_features_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_music_features_proto_rawDesc), len(file_music_features_proto_rawDesc)))
	})
	return file_music_features_proto_rawDescData
}

var file_music_features_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_music_features_proto_goTypes = []any{
	(*ArtistGetRequest)(nil),     // 0: flixur.music_features.ArtistGetRequest
	(*ArtistGetResponse)(nil),    // 1: flixur.music_features.ArtistGetResponse
	(*ArtistSearchRequest)(nil),  // 2: flixur.music_features.ArtistSearchRequest
	(*ArtistSearchResponse)(nil), // 3: flixur.music_features.ArtistSearchResponse
	(*AlbumGetRequest)(nil),      // 4: flixur.music_features.AlbumGetRequest
	(*AlbumGetResponse)(nil),     // 5: flixur.music_features.AlbumGetResponse
	(*AlbumSearchRequest)(nil),   // 6: flixur.music_features.AlbumSearchRequest
	(*AlbumSearchResponse)(nil),  // 7: flixur.music_features.AlbumSearchResponse
	(*TrackGetRequest)(nil),      // 8: flixur.music_features.TrackGetRequest
	(*TrackGetResponse)(nil),     // 9: flixur.music_features.TrackGetResponse
	(*TrackSearchRequest)(nil),   // 10: flixur.music_features.TrackSearchRequest
	(*TrackSearchResponse)(nil),  // 11: flixur.music_features.TrackSearchResponse
	(*Artist)(nil),               // 12: flixur.music.Artist
	(*Album)(nil),                // 13: flixur.music.Album
	(*Track)(nil),                // 14: flixur.music.Track
}
var file_music_features_proto_depIdxs = []int32{
	12, // 0: flixur.music_features.ArtistGetResponse.artist:type_name -> flixur.music.Artist
	12, // 1: flixur.music_features.ArtistSearchResponse.results:type_name -> flixur.music.Artist
	13, // 2: flixur.music_features.AlbumGetResponse.album:type_name -> flixur.music.Album
	13, // 3: flixur.music_features.AlbumSearchResponse.results:type_name -> flixur.music.Album
	14, // 4: flixur.music_features.TrackGetResponse.track:type_name -> flixur.music.Track
	14, // 5: flixur.music_features.TrackSearchResponse.results:type_name -> flixur.music.Track
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_music_features_proto_init() }
func file_music_features_proto_init() {
	if File_music_features_proto != nil {
		return
	}
	file_music_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_music_features_proto_rawDesc), len(file_music_features_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_music_features_proto_goTypes,
		DependencyIndexes: file_music_features_proto_depIdxs,
		MessageInfos:      file_music_features_proto_msgTypes,
	}.Build()
	File_music_features_proto = out.File
	file_music_features_proto_goTypes = nil
	file_music_features_proto_depIdxs = nil
}
