// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: music.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlbumType int32

const (
	AlbumType_SINGLE AlbumType = 0
	AlbumType_ALBUM  AlbumType = 1
)

// Enum value maps for AlbumType.
var (
	AlbumType_name = map[int32]string{
		0: "SINGLE",
		1: "ALBUM",
	}
	AlbumType_value = map[string]int32{
		"SINGLE": 0,
		"ALBUM":  1,
	}
)

func (x AlbumType) Enum() *AlbumType {
	p := new(AlbumType)
	*p = x
	return p
}

func (x AlbumType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlbumType) Descriptor() protoreflect.EnumDescriptor {
	return file_music_proto_enumTypes[0].Descriptor()
}

func (AlbumType) Type() protoreflect.EnumType {
	return &file_music_proto_enumTypes[0]
}

func (x AlbumType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlbumType.Descriptor instead.
func (AlbumType) EnumDescriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{0}
}

type TrackExplicitness int32

const (
	// Normal
	TrackExplicitness_CLEAN TrackExplicitness = 0
	// Explicit
	TrackExplicitness_EXPLICIT TrackExplicitness = 1
	// Rated X
	TrackExplicitness_RESTRICTED TrackExplicitness = 2
)

// Enum value maps for TrackExplicitness.
var (
	TrackExplicitness_name = map[int32]string{
		0: "CLEAN",
		1: "EXPLICIT",
		2: "RESTRICTED",
	}
	TrackExplicitness_value = map[string]int32{
		"CLEAN":      0,
		"EXPLICIT":   1,
		"RESTRICTED": 2,
	}
)

func (x TrackExplicitness) Enum() *TrackExplicitness {
	p := new(TrackExplicitness)
	*p = x
	return p
}

func (x TrackExplicitness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackExplicitness) Descriptor() protoreflect.EnumDescriptor {
	return file_music_proto_enumTypes[1].Descriptor()
}

func (TrackExplicitness) Type() protoreflect.EnumType {
	return &file_music_proto_enumTypes[1]
}

func (x TrackExplicitness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackExplicitness.Descriptor instead.
func (TrackExplicitness) EnumDescriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{1}
}

// Usually an artist returned from a provider.
type Artist struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the artist from the provider.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// ID of the plugin that provided this artist.
	Provider string `protobuf:"bytes,7,opt,name=provider,proto3" json:"provider"`
	// Name of the artist.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// Icon URL for the artist. Should be accessible via HTTP with CORS.
	Icon *string `protobuf:"bytes,3,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	// Description of the artist.
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Geographical location of the artist.
	Location *string `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	// Follower count for the artist. (using the platform of choice)
	Followers     *int64 `protobuf:"varint,6,opt,name=followers,proto3,oneof" json:"followers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artist) Reset() {
	*x = Artist{}
	mi := &file_music_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_music_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{0}
}

func (x *Artist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artist) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *Artist) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Artist) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *Artist) GetFollowers() int64 {
	if x != nil && x.Followers != nil {
		return *x.Followers
	}
	return 0
}

// An artist stored locally.
type LocalArtist struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for the artist. (unique across providers)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// Base metadata for the artist.
	Metadata *Artist `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Rating for the artist.
	Rating        *int32 `protobuf:"varint,3,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalArtist) Reset() {
	*x = LocalArtist{}
	mi := &file_music_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalArtist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalArtist) ProtoMessage() {}

func (x *LocalArtist) ProtoReflect() protoreflect.Message {
	mi := &file_music_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalArtist.ProtoReflect.Descriptor instead.
func (*LocalArtist) Descriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{1}
}

func (x *LocalArtist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocalArtist) GetMetadata() *Artist {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LocalArtist) GetRating() int32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

type Album struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for the album.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// IDs of artists on this album.
	Artists []string `protobuf:"bytes,2,rep,name=artists,proto3" json:"artists"`
	// Name of the album.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	// Cover URL for album art. Should be accessible via HTTP with CORS.
	Icon *string `protobuf:"bytes,4,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	// Unix timestamp the album was released. (in seconds)
	Date int64 `protobuf:"varint,5,opt,name=date,proto3" json:"date"`
	// Type of the album.
	Type AlbumType `protobuf:"varint,6,opt,name=type,proto3,enum=flixur.music.AlbumType" json:"type"`
	// Rating for the track.
	Rating *int32 `protobuf:"varint,8,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	// Description of the album.
	Description *string `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// List of genres for the album.
	Genres        []string `protobuf:"bytes,9,rep,name=genres,proto3" json:"genres"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_music_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_music_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{2}
}

func (x *Album) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Album) GetArtists() []string {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Album) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Album) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *Album) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Album) GetType() AlbumType {
	if x != nil {
		return x.Type
	}
	return AlbumType_SINGLE
}

func (x *Album) GetRating() int32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *Album) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Album) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type Track struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for the track.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// Unique ISRC of the track. May be unofficial.
	Isrc string `protobuf:"bytes,8,opt,name=isrc,proto3" json:"isrc"`
	// IDs of artists on this track.
	Artists []string `protobuf:"bytes,2,rep,name=artists,proto3" json:"artists"`
	// Title of the track.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title"`
	// Track number in the album.
	Index int32 `protobuf:"varint,4,opt,name=index,proto3" json:"index"`
	// Duration in ms of the track.
	Duration int64 `protobuf:"varint,5,opt,name=duration,proto3" json:"duration"`
	// Rating for the track.
	Rating *int32 `protobuf:"varint,6,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	// The explicitness of the track.
	Explicitness  TrackExplicitness `protobuf:"varint,7,opt,name=explicitness,proto3,enum=flixur.music.TrackExplicitness" json:"explicitness"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_music_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_music_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_music_proto_rawDescGZIP(), []int{3}
}

func (x *Track) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Track) GetIsrc() string {
	if x != nil {
		return x.Isrc
	}
	return ""
}

func (x *Track) GetArtists() []string {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Track) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Track) GetRating() int32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *Track) GetExplicitness() TrackExplicitness {
	if x != nil {
		return x.Explicitness
	}
	return TrackExplicitness_CLEAN
}

var File_music_proto protoreflect.FileDescriptor

const file_music_proto_rawDesc = "" +
	"\n" +
	"\vmusic.proto\x12\fflixur.music\"\x80\x02\n" +
	"\x06Artist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\a \x01(\tR\bprovider\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\x04icon\x18\x03 \x01(\tH\x00R\x04icon\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\blocation\x18\x05 \x01(\tH\x02R\blocation\x88\x01\x01\x12!\n" +
	"\tfollowers\x18\x06 \x01(\x03H\x03R\tfollowers\x88\x01\x01B\a\n" +
	"\x05_iconB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_locationB\f\n" +
	"\n" +
	"_followers\"w\n" +
	"\vLocalArtist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.flixur.music.ArtistR\bmetadata\x12\x1b\n" +
	"\x06rating\x18\x03 \x01(\x05H\x00R\x06rating\x88\x01\x01B\t\n" +
	"\a_rating\"\x9f\x02\n" +
	"\x05Album\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aartists\x18\x02 \x03(\tR\aartists\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\x04icon\x18\x04 \x01(\tH\x00R\x04icon\x88\x01\x01\x12\x12\n" +
	"\x04date\x18\x05 \x01(\x03R\x04date\x12+\n" +
	"\x04type\x18\x06 \x01(\x0e2\x17.flixur.music.AlbumTypeR\x04type\x12\x1b\n" +
	"\x06rating\x18\b \x01(\x05H\x01R\x06rating\x88\x01\x01\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06genres\x18\t \x03(\tR\x06genresB\a\n" +
	"\x05_iconB\t\n" +
	"\a_ratingB\x0e\n" +
	"\f_description\"\xfa\x01\n" +
	"\x05Track\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04isrc\x18\b \x01(\tR\x04isrc\x12\x18\n" +
	"\aartists\x18\x02 \x03(\tR\aartists\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x12\x1b\n" +
	"\x06rating\x18\x06 \x01(\x05H\x00R\x06rating\x88\x01\x01\x12C\n" +
	"\fexplicitness\x18\a \x01(\x0e2\x1f.flixur.music.TrackExplicitnessR\fexplicitnessB\t\n" +
	"\a_rating*\"\n" +
	"\tAlbumType\x12\n" +
	"\n" +
	"\x06SINGLE\x10\x00\x12\t\n" +
	"\x05ALBUM\x10\x01*<\n" +
	"\x11TrackExplicitness\x12\t\n" +
	"\x05CLEAN\x10\x00\x12\f\n" +
	"\bEXPLICIT\x10\x01\x12\x0e\n" +
	"\n" +
	"RESTRICTED\x10\x02B&Z$github.com/flixurapp/flixur/proto/gob\x06proto3"

var (
	file_music_proto_rawDescOnce sync.Once
	file_music_proto_rawDescData []byte
)

func file_music_proto_rawDescGZIP() []byte {
	file_music_proto_rawDescOnce.Do(func() {
		file_music_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_music_proto_rawDesc), len(file_music_proto_rawDesc)))
	})
	return file_music_proto_rawDescData
}

var file_music_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_music_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_music_proto_goTypes = []any{
	(AlbumType)(0),         // 0: flixur.music.AlbumType
	(TrackExplicitness)(0), // 1: flixur.music.TrackExplicitness
	(*Artist)(nil),         // 2: flixur.music.Artist
	(*LocalArtist)(nil),    // 3: flixur.music.LocalArtist
	(*Album)(nil),          // 4: flixur.music.Album
	(*Track)(nil),          // 5: flixur.music.Track
}
var file_music_proto_depIdxs = []int32{
	2, // 0: flixur.music.LocalArtist.metadata:type_name -> flixur.music.Artist
	0, // 1: flixur.music.Album.type:type_name -> flixur.music.AlbumType
	1, // 2: flixur.music.Track.explicitness:type_name -> flixur.music.TrackExplicitness
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_music_proto_init() }
func file_music_proto_init() {
	if File_music_proto != nil {
		return
	}
	file_music_proto_msgTypes[0].OneofWrappers = []any{}
	file_music_proto_msgTypes[1].OneofWrappers = []any{}
	file_music_proto_msgTypes[2].OneofWrappers = []any{}
	file_music_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_music_proto_rawDesc), len(file_music_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_music_proto_goTypes,
		DependencyIndexes: file_music_proto_depIdxs,
		EnumInfos:         file_music_proto_enumTypes,
		MessageInfos:      file_music_proto_msgTypes,
	}.Build()
	File_music_proto = out.File
	file_music_proto_goTypes = nil
	file_music_proto_depIdxs = nil
}
