// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: plugins.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_INIT             PacketType = 0 // PacketInit
	PacketType_INFO             PacketType = 1 // PacketInfo
	PacketType_FEATURE_REQUEST  PacketType = 2 // PacketFeatureRequest
	PacketType_FEATURE_RESPONSE PacketType = 3 // PacketFeatureResponse
	PacketType_DESTROY          PacketType = 4 // PacketDestroy
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "INIT",
		1: "INFO",
		2: "FEATURE_REQUEST",
		3: "FEATURE_RESPONSE",
		4: "DESTROY",
	}
	PacketType_value = map[string]int32{
		"INIT":             0,
		"INFO":             1,
		"FEATURE_REQUEST":  2,
		"FEATURE_RESPONSE": 3,
		"DESTROY":          4,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugins_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_plugins_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{0}
}

// Functions that plugins can implement.
type Features int32

const (
	// Get a specific artist by internal ID.
	Features_ARTIST_GET Features = 0
	// Search for an artist by name.
	Features_ARTIST_SEARCH Features = 1
	// Get a specific album by internal ID.
	Features_ALBUM_GET Features = 2
	// Search for an album by name.
	Features_ALBUM_SEARCH Features = 3
	// Get a specific track by internal ID.
	Features_TRACK_GET Features = 4
	// Search for a track by name.
	Features_TRACK_SEARCH Features = 5
)

// Enum value maps for Features.
var (
	Features_name = map[int32]string{
		0: "ARTIST_GET",
		1: "ARTIST_SEARCH",
		2: "ALBUM_GET",
		3: "ALBUM_SEARCH",
		4: "TRACK_GET",
		5: "TRACK_SEARCH",
	}
	Features_value = map[string]int32{
		"ARTIST_GET":    0,
		"ARTIST_SEARCH": 1,
		"ALBUM_GET":     2,
		"ALBUM_SEARCH":  3,
		"TRACK_GET":     4,
		"TRACK_SEARCH":  5,
	}
)

func (x Features) Enum() *Features {
	p := new(Features)
	*p = x
	return p
}

func (x Features) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Features) Descriptor() protoreflect.EnumDescriptor {
	return file_plugins_proto_enumTypes[1].Descriptor()
}

func (Features) Type() protoreflect.EnumType {
	return &file_plugins_proto_enumTypes[1]
}

func (x Features) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Features.Descriptor instead.
func (Features) EnumDescriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{1}
}

// Packets sent between server and plugin.
type PluginPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of the packet.
	Type PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=flixur.plugins.PacketType" json:"type"`
	// Identifier for the packet. (used to respond to certain requests)
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id"`
	// The actual packet data. (a below protobuf)
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginPacket) Reset() {
	*x = PluginPacket{}
	mi := &file_plugins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginPacket) ProtoMessage() {}

func (x *PluginPacket) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginPacket.ProtoReflect.Descriptor instead.
func (*PluginPacket) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{0}
}

func (x *PluginPacket) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_INIT
}

func (x *PluginPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Sent by the server to tell a plugin to initialize.
type PacketInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current numerical version of the server.
	Version       int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketInit) Reset() {
	*x = PacketInit{}
	mi := &file_plugins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketInit) ProtoMessage() {}

func (x *PacketInit) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketInit.ProtoReflect.Descriptor instead.
func (*PacketInit) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{1}
}

func (x *PacketInit) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Sent by a plugin to identify itself.
type PacketInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique Plugin ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// Numerical version of the plugin.
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version"`
	// Minimum required app version for the plugin to load.
	MinVersion int32 `protobuf:"varint,3,opt,name=min_version,json=minVersion,proto3" json:"min_version"`
	// List of plugin IDs that should be loaded before this plugin.
	Dependencies []string `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies"`
	// List of features this plugin implements.
	Features []Features `protobuf:"varint,8,rep,packed,name=features,proto3,enum=flixur.plugins.Features" json:"features"`
	// Name of the plugin.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	// Should be the full identifier of an Iconify icon for this plugin. (https://icon-sets.iconify.design)
	Icon string `protobuf:"bytes,10,opt,name=icon,proto3" json:"icon"`
	// Short description of the plugin.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	// Name of the plugin author.
	Author string `protobuf:"bytes,7,opt,name=author,proto3" json:"author"`
	// Direct link to the source code of the plugin.
	Url           string `protobuf:"bytes,9,opt,name=url,proto3" json:"url"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketInfo) Reset() {
	*x = PacketInfo{}
	mi := &file_plugins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketInfo) ProtoMessage() {}

func (x *PacketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketInfo.ProtoReflect.Descriptor instead.
func (*PacketInfo) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{2}
}

func (x *PacketInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PacketInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PacketInfo) GetMinVersion() int32 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

func (x *PacketInfo) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *PacketInfo) GetFeatures() []Features {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PacketInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PacketInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PacketInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PacketInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PacketInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Calls a feature implemented by the plugin.
type PacketFeatureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the feature to call.
	Feature Features `protobuf:"varint,1,opt,name=feature,proto3,enum=flixur.plugins.Features" json:"feature"`
	// Request payload from `features` to use.
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketFeatureRequest) Reset() {
	*x = PacketFeatureRequest{}
	mi := &file_plugins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketFeatureRequest) ProtoMessage() {}

func (x *PacketFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketFeatureRequest.ProtoReflect.Descriptor instead.
func (*PacketFeatureRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{3}
}

func (x *PacketFeatureRequest) GetFeature() Features {
	if x != nil {
		return x.Feature
	}
	return Features_ARTIST_GET
}

func (x *PacketFeatureRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Response from a feature request.
type PacketFeatureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the feature that created the response.
	Feature Features `protobuf:"varint,1,opt,name=feature,proto3,enum=flixur.plugins.Features" json:"feature"`
	// Response payload from `features` matching the feature.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3,oneof" json:"payload"`
	// Optional error response from the request.
	Error         *FeatureError `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketFeatureResponse) Reset() {
	*x = PacketFeatureResponse{}
	mi := &file_plugins_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketFeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketFeatureResponse) ProtoMessage() {}

func (x *PacketFeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketFeatureResponse.ProtoReflect.Descriptor instead.
func (*PacketFeatureResponse) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{4}
}

func (x *PacketFeatureResponse) GetFeature() Features {
	if x != nil {
		return x.Feature
	}
	return Features_ARTIST_GET
}

func (x *PacketFeatureResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PacketFeatureResponse) GetError() *FeatureError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Used when the server is shutting down or plugin is being uninstalled.
type PacketDestroy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketDestroy) Reset() {
	*x = PacketDestroy{}
	mi := &file_plugins_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketDestroy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketDestroy) ProtoMessage() {}

func (x *PacketDestroy) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketDestroy.ProtoReflect.Descriptor instead.
func (*PacketDestroy) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{5}
}

var File_plugins_proto protoreflect.FileDescriptor

const file_plugins_proto_rawDesc = "" +
	"\n" +
	"\rplugins.proto\x12\x0eflixur.plugins\x1a\x0efeatures.proto\"b\n" +
	"\fPluginPacket\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.flixur.plugins.PacketTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"&\n" +
	"\n" +
	"PacketInit\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\"\xa5\x02\n" +
	"\n" +
	"PacketInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1f\n" +
	"\vmin_version\x18\x03 \x01(\x05R\n" +
	"minVersion\x12\"\n" +
	"\fdependencies\x18\x04 \x03(\tR\fdependencies\x124\n" +
	"\bfeatures\x18\b \x03(\x0e2\x18.flixur.plugins.FeaturesR\bfeatures\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\n" +
	" \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12\x10\n" +
	"\x03url\x18\t \x01(\tR\x03url\"d\n" +
	"\x14PacketFeatureRequest\x122\n" +
	"\afeature\x18\x01 \x01(\x0e2\x18.flixur.plugins.FeaturesR\afeature\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xba\x01\n" +
	"\x15PacketFeatureResponse\x122\n" +
	"\afeature\x18\x01 \x01(\x0e2\x18.flixur.plugins.FeaturesR\afeature\x12\x1d\n" +
	"\apayload\x18\x02 \x01(\fH\x00R\apayload\x88\x01\x01\x128\n" +
	"\x05error\x18\x03 \x01(\v2\x1d.flixur.features.FeatureErrorH\x01R\x05error\x88\x01\x01B\n" +
	"\n" +
	"\b_payloadB\b\n" +
	"\x06_error\"\x0f\n" +
	"\rPacketDestroy*X\n" +
	"\n" +
	"PacketType\x12\b\n" +
	"\x04INIT\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\x13\n" +
	"\x0fFEATURE_REQUEST\x10\x02\x12\x14\n" +
	"\x10FEATURE_RESPONSE\x10\x03\x12\v\n" +
	"\aDESTROY\x10\x04*o\n" +
	"\bFeatures\x12\x0e\n" +
	"\n" +
	"ARTIST_GET\x10\x00\x12\x11\n" +
	"\rARTIST_SEARCH\x10\x01\x12\r\n" +
	"\tALBUM_GET\x10\x02\x12\x10\n" +
	"\fALBUM_SEARCH\x10\x03\x12\r\n" +
	"\tTRACK_GET\x10\x04\x12\x10\n" +
	"\fTRACK_SEARCH\x10\x05B&Z$github.com/flixurapp/flixur/proto/gob\x06proto3"

var (
	file_plugins_proto_rawDescOnce sync.Once
	file_plugins_proto_rawDescData []byte
)

func file_plugins_proto_rawDescGZIP() []byte {
	file_plugins_proto_rawDescOnce.Do(func() {
		file_plugins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_proto_rawDesc), len(file_plugins_proto_rawDesc)))
	})
	return file_plugins_proto_rawDescData
}

var file_plugins_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugins_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugins_proto_goTypes = []any{
	(PacketType)(0),               // 0: flixur.plugins.PacketType
	(Features)(0),                 // 1: flixur.plugins.Features
	(*PluginPacket)(nil),          // 2: flixur.plugins.PluginPacket
	(*PacketInit)(nil),            // 3: flixur.plugins.PacketInit
	(*PacketInfo)(nil),            // 4: flixur.plugins.PacketInfo
	(*PacketFeatureRequest)(nil),  // 5: flixur.plugins.PacketFeatureRequest
	(*PacketFeatureResponse)(nil), // 6: flixur.plugins.PacketFeatureResponse
	(*PacketDestroy)(nil),         // 7: flixur.plugins.PacketDestroy
	(*FeatureError)(nil),          // 8: flixur.features.FeatureError
}
var file_plugins_proto_depIdxs = []int32{
	0, // 0: flixur.plugins.PluginPacket.type:type_name -> flixur.plugins.PacketType
	1, // 1: flixur.plugins.PacketInfo.features:type_name -> flixur.plugins.Features
	1, // 2: flixur.plugins.PacketFeatureRequest.feature:type_name -> flixur.plugins.Features
	1, // 3: flixur.plugins.PacketFeatureResponse.feature:type_name -> flixur.plugins.Features
	8, // 4: flixur.plugins.PacketFeatureResponse.error:type_name -> flixur.features.FeatureError
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_plugins_proto_init() }
func file_plugins_proto_init() {
	if File_plugins_proto != nil {
		return
	}
	file_features_proto_init()
	file_plugins_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_proto_rawDesc), len(file_plugins_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugins_proto_goTypes,
		DependencyIndexes: file_plugins_proto_depIdxs,
		EnumInfos:         file_plugins_proto_enumTypes,
		MessageInfos:      file_plugins_proto_msgTypes,
	}.Build()
	File_plugins_proto = out.File
	file_plugins_proto_goTypes = nil
	file_plugins_proto_depIdxs = nil
}
