// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: plugins.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_INIT          PacketType = 0 // PacketInit
	PacketType_ARTIST_SEARCH PacketType = 1 // PacketArtistSearch
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "INIT",
		1: "ARTIST_SEARCH",
	}
	PacketType_value = map[string]int32{
		"INIT":          0,
		"ARTIST_SEARCH": 1,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugins_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_plugins_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{0}
}

type PluginType int32

const (
	PluginType_SERVER         PluginType = 0 // Provides additional functions to server.
	PluginType_PROVIDER_AUDIO PluginType = 1 // Provides audio metadata. (artist/album/track)
	PluginType_PROVIDER_VIDEO PluginType = 2 // Provides video metadata. (unused)
	PluginType_DOWNLOADER     PluginType = 3 // Downloads requested content.
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "SERVER",
		1: "PROVIDER_AUDIO",
		2: "PROVIDER_VIDEO",
		3: "DOWNLOADER",
	}
	PluginType_value = map[string]int32{
		"SERVER":         0,
		"PROVIDER_AUDIO": 1,
		"PROVIDER_VIDEO": 2,
		"DOWNLOADER":     3,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugins_proto_enumTypes[1].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_plugins_proto_enumTypes[1]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{1}
}

// Packets sent to the server from a plugin.
type IncomingPluginPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of the packet.
	Type PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=flixur.PacketType" json:"type"`
	// Identifier for the packet. (used to respond to certain requests)
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id"`
	// The actual packet data. (a protobuf)
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *IncomingPluginPacket) Reset() {
	*x = IncomingPluginPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugins_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncomingPluginPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingPluginPacket) ProtoMessage() {}

func (x *IncomingPluginPacket) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingPluginPacket.ProtoReflect.Descriptor instead.
func (*IncomingPluginPacket) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{0}
}

func (x *IncomingPluginPacket) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_INIT
}

func (x *IncomingPluginPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IncomingPluginPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Packets sent to a plugin from the server.
type OutgoingPluginPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of the packet.
	Type PacketType `protobuf:"varint,1,opt,name=type,proto3,enum=flixur.PacketType" json:"type"`
	// Identifier for the packet. (echoed back in the response)
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id"`
	// The actual packet data. (a protobuf)
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *OutgoingPluginPacket) Reset() {
	*x = OutgoingPluginPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugins_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutgoingPluginPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingPluginPacket) ProtoMessage() {}

func (x *OutgoingPluginPacket) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingPluginPacket.ProtoReflect.Descriptor instead.
func (*OutgoingPluginPacket) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{1}
}

func (x *OutgoingPluginPacket) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_INIT
}

func (x *OutgoingPluginPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutgoingPluginPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Sent by a plugin to identify itself when registered.
type PacketInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique Plugin ID.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id"`
	// Version string.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version"`
	// Type of the plugin.
	Type PluginType `protobuf:"varint,4,opt,name=type,proto3,enum=flixur.PluginType" json:"type"`
	// Name of the plugin.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	// Short description of the plugin.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	// Name of the plugin author.
	Author string `protobuf:"bytes,7,opt,name=author,proto3" json:"author"`
}

func (x *PacketInit) Reset() {
	*x = PacketInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugins_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketInit) ProtoMessage() {}

func (x *PacketInit) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketInit.ProtoReflect.Descriptor instead.
func (*PacketInit) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{2}
}

func (x *PacketInit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PacketInit) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PacketInit) GetType() PluginType {
	if x != nil {
		return x.Type
	}
	return PluginType_SERVER
}

func (x *PacketInit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PacketInit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PacketInit) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

// Search for an artist using this plugin.
// (supports: )
type PacketArtistSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,4,opt,name=query,proto3" json:"query"`
}

func (x *PacketArtistSearch) Reset() {
	*x = PacketArtistSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugins_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketArtistSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketArtistSearch) ProtoMessage() {}

func (x *PacketArtistSearch) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketArtistSearch.ProtoReflect.Descriptor instead.
func (*PacketArtistSearch) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{3}
}

func (x *PacketArtistSearch) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

var File_plugins_proto protoreflect.FileDescriptor

var file_plugins_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x22, 0x62, 0x0a, 0x14, 0x49, 0x6e, 0x63, 0x6f, 0x6d,
	0x69, 0x6e, 0x67, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x62, 0x0a, 0x14, 0x4f,
	0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xac, 0x01, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x2e,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x2a,
	0x0a, 0x12, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2a, 0x29, 0x0a, 0x0a, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x49, 0x54,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x52, 0x54, 0x49, 0x53, 0x54, 0x5f, 0x53, 0x45, 0x41,
	0x52, 0x43, 0x48, 0x10, 0x01, 0x2a, 0x50, 0x0a, 0x0a, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x41, 0x55, 0x44, 0x49,
	0x4f, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f,
	0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x4f, 0x57, 0x4e, 0x4c,
	0x4f, 0x41, 0x44, 0x45, 0x52, 0x10, 0x03, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x61, 0x70, 0x70, 0x2f,
	0x66, 0x6c, 0x69, 0x78, 0x75, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugins_proto_rawDescOnce sync.Once
	file_plugins_proto_rawDescData = file_plugins_proto_rawDesc
)

func file_plugins_proto_rawDescGZIP() []byte {
	file_plugins_proto_rawDescOnce.Do(func() {
		file_plugins_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugins_proto_rawDescData)
	})
	return file_plugins_proto_rawDescData
}

var file_plugins_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugins_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plugins_proto_goTypes = []interface{}{
	(PacketType)(0),              // 0: flixur.PacketType
	(PluginType)(0),              // 1: flixur.PluginType
	(*IncomingPluginPacket)(nil), // 2: flixur.IncomingPluginPacket
	(*OutgoingPluginPacket)(nil), // 3: flixur.OutgoingPluginPacket
	(*PacketInit)(nil),           // 4: flixur.PacketInit
	(*PacketArtistSearch)(nil),   // 5: flixur.PacketArtistSearch
}
var file_plugins_proto_depIdxs = []int32{
	0, // 0: flixur.IncomingPluginPacket.type:type_name -> flixur.PacketType
	0, // 1: flixur.OutgoingPluginPacket.type:type_name -> flixur.PacketType
	1, // 2: flixur.PacketInit.type:type_name -> flixur.PluginType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plugins_proto_init() }
func file_plugins_proto_init() {
	if File_plugins_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugins_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncomingPluginPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugins_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutgoingPluginPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugins_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugins_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketArtistSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugins_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugins_proto_goTypes,
		DependencyIndexes: file_plugins_proto_depIdxs,
		EnumInfos:         file_plugins_proto_enumTypes,
		MessageInfos:      file_plugins_proto_msgTypes,
	}.Build()
	File_plugins_proto = out.File
	file_plugins_proto_rawDesc = nil
	file_plugins_proto_goTypes = nil
	file_plugins_proto_depIdxs = nil
}
