// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: plugins.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message for RPC calls that don't require input.
type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_plugins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{0}
}

// Plugin metadata returned by GetPluginInfo.
type PluginInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique Plugin ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	// Name of the plugin.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// Numerical version of the plugin.
	Version int32 `protobuf:"varint,3,opt,name=version,proto3" json:"version"`
	// Minimum required app version for the plugin to load.
	MinVersion int32 `protobuf:"varint,4,opt,name=min_version,json=minVersion,proto3" json:"min_version"`
	// List of plugin IDs that should be loaded before this plugin.
	Dependencies []string `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies"`
	// List of feature names this plugin implements.
	Features []string `protobuf:"bytes,6,rep,name=features,proto3" json:"features"`
	// Should be the full identifier of an Iconify icon for this plugin. (https://icon-sets.iconify.design)
	Icon string `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon"`
	// Short description of the plugin.
	Description string `protobuf:"bytes,8,opt,name=description,proto3" json:"description"`
	// Name of the plugin author.
	Author string `protobuf:"bytes,9,opt,name=author,proto3" json:"author"`
	// Direct link to the source code of the plugin.
	Url           string `protobuf:"bytes,10,opt,name=url,proto3" json:"url"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugins_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PluginInfo) GetMinVersion() int32 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

func (x *PluginInfo) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *PluginInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PluginInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_plugins_proto protoreflect.FileDescriptor

const file_plugins_proto_rawDesc = "" +
	"\n" +
	"\rplugins.proto\x12\x0eflixur.plugins\x1a\x14music_features.proto\"\x0e\n" +
	"\fEmptyRequest\"\x8b\x02\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x1f\n" +
	"\vmin_version\x18\x04 \x01(\x05R\n" +
	"minVersion\x12\"\n" +
	"\fdependencies\x18\x05 \x03(\tR\fdependencies\x12\x1a\n" +
	"\bfeatures\x18\x06 \x03(\tR\bfeatures\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\t \x01(\tR\x06author\x12\x10\n" +
	"\x03url\x18\n" +
	" \x01(\tR\x03url2\xa8\x05\n" +
	"\fFlixurPlugin\x12I\n" +
	"\rGetPluginInfo\x12\x1c.flixur.plugins.EmptyRequest\x1a\x1a.flixur.plugins.PluginInfo\x12^\n" +
	"\tArtistGet\x12'.flixur.music_features.ArtistGetRequest\x1a(.flixur.music_features.ArtistGetResponse\x12g\n" +
	"\fArtistSearch\x12*.flixur.music_features.ArtistSearchRequest\x1a+.flixur.music_features.ArtistSearchResponse\x12[\n" +
	"\bAlbumGet\x12&.flixur.music_features.AlbumGetRequest\x1a'.flixur.music_features.AlbumGetResponse\x12d\n" +
	"\vAlbumSearch\x12).flixur.music_features.AlbumSearchRequest\x1a*.flixur.music_features.AlbumSearchResponse\x12[\n" +
	"\bTrackGet\x12&.flixur.music_features.TrackGetRequest\x1a'.flixur.music_features.TrackGetResponse\x12d\n" +
	"\vTrackSearch\x12).flixur.music_features.TrackSearchRequest\x1a*.flixur.music_features.TrackSearchResponseB&Z$github.com/flixurapp/flixur/proto/gob\x06proto3"

var (
	file_plugins_proto_rawDescOnce sync.Once
	file_plugins_proto_rawDescData []byte
)

func file_plugins_proto_rawDescGZIP() []byte {
	file_plugins_proto_rawDescOnce.Do(func() {
		file_plugins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_proto_rawDesc), len(file_plugins_proto_rawDesc)))
	})
	return file_plugins_proto_rawDescData
}

var file_plugins_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugins_proto_goTypes = []any{
	(*EmptyRequest)(nil),         // 0: flixur.plugins.EmptyRequest
	(*PluginInfo)(nil),           // 1: flixur.plugins.PluginInfo
	(*ArtistGetRequest)(nil),     // 2: flixur.music_features.ArtistGetRequest
	(*ArtistSearchRequest)(nil),  // 3: flixur.music_features.ArtistSearchRequest
	(*AlbumGetRequest)(nil),      // 4: flixur.music_features.AlbumGetRequest
	(*AlbumSearchRequest)(nil),   // 5: flixur.music_features.AlbumSearchRequest
	(*TrackGetRequest)(nil),      // 6: flixur.music_features.TrackGetRequest
	(*TrackSearchRequest)(nil),   // 7: flixur.music_features.TrackSearchRequest
	(*ArtistGetResponse)(nil),    // 8: flixur.music_features.ArtistGetResponse
	(*ArtistSearchResponse)(nil), // 9: flixur.music_features.ArtistSearchResponse
	(*AlbumGetResponse)(nil),     // 10: flixur.music_features.AlbumGetResponse
	(*AlbumSearchResponse)(nil),  // 11: flixur.music_features.AlbumSearchResponse
	(*TrackGetResponse)(nil),     // 12: flixur.music_features.TrackGetResponse
	(*TrackSearchResponse)(nil),  // 13: flixur.music_features.TrackSearchResponse
}
var file_plugins_proto_depIdxs = []int32{
	0,  // 0: flixur.plugins.FlixurPlugin.GetPluginInfo:input_type -> flixur.plugins.EmptyRequest
	2,  // 1: flixur.plugins.FlixurPlugin.ArtistGet:input_type -> flixur.music_features.ArtistGetRequest
	3,  // 2: flixur.plugins.FlixurPlugin.ArtistSearch:input_type -> flixur.music_features.ArtistSearchRequest
	4,  // 3: flixur.plugins.FlixurPlugin.AlbumGet:input_type -> flixur.music_features.AlbumGetRequest
	5,  // 4: flixur.plugins.FlixurPlugin.AlbumSearch:input_type -> flixur.music_features.AlbumSearchRequest
	6,  // 5: flixur.plugins.FlixurPlugin.TrackGet:input_type -> flixur.music_features.TrackGetRequest
	7,  // 6: flixur.plugins.FlixurPlugin.TrackSearch:input_type -> flixur.music_features.TrackSearchRequest
	1,  // 7: flixur.plugins.FlixurPlugin.GetPluginInfo:output_type -> flixur.plugins.PluginInfo
	8,  // 8: flixur.plugins.FlixurPlugin.ArtistGet:output_type -> flixur.music_features.ArtistGetResponse
	9,  // 9: flixur.plugins.FlixurPlugin.ArtistSearch:output_type -> flixur.music_features.ArtistSearchResponse
	10, // 10: flixur.plugins.FlixurPlugin.AlbumGet:output_type -> flixur.music_features.AlbumGetResponse
	11, // 11: flixur.plugins.FlixurPlugin.AlbumSearch:output_type -> flixur.music_features.AlbumSearchResponse
	12, // 12: flixur.plugins.FlixurPlugin.TrackGet:output_type -> flixur.music_features.TrackGetResponse
	13, // 13: flixur.plugins.FlixurPlugin.TrackSearch:output_type -> flixur.music_features.TrackSearchResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_plugins_proto_init() }
func file_plugins_proto_init() {
	if File_plugins_proto != nil {
		return
	}
	file_music_features_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_proto_rawDesc), len(file_plugins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_proto_goTypes,
		DependencyIndexes: file_plugins_proto_depIdxs,
		MessageInfos:      file_plugins_proto_msgTypes,
	}.Build()
	File_plugins_proto = out.File
	file_plugins_proto_goTypes = nil
	file_plugins_proto_depIdxs = nil
}
