// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: plugins.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlixurPlugin_GetPluginInfo_FullMethodName = "/flixur.plugins.FlixurPlugin/GetPluginInfo"
	FlixurPlugin_ArtistGet_FullMethodName     = "/flixur.plugins.FlixurPlugin/ArtistGet"
	FlixurPlugin_ArtistSearch_FullMethodName  = "/flixur.plugins.FlixurPlugin/ArtistSearch"
	FlixurPlugin_AlbumGet_FullMethodName      = "/flixur.plugins.FlixurPlugin/AlbumGet"
	FlixurPlugin_AlbumSearch_FullMethodName   = "/flixur.plugins.FlixurPlugin/AlbumSearch"
	FlixurPlugin_TrackGet_FullMethodName      = "/flixur.plugins.FlixurPlugin/TrackGet"
	FlixurPlugin_TrackSearch_FullMethodName   = "/flixur.plugins.FlixurPlugin/TrackSearch"
)

// FlixurPluginClient is the client API for FlixurPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The main plugin service. Plugins implement this gRPC service.
type FlixurPluginClient interface {
	// Get plugin metadata and capabilities.
	GetPluginInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*PluginInfo, error)
	// === Artist Methods ===
	// Get a specific artist by ID.
	ArtistGet(ctx context.Context, in *ArtistGetRequest, opts ...grpc.CallOption) (*ArtistGetResponse, error)
	// Search for artists by name.
	ArtistSearch(ctx context.Context, in *ArtistSearchRequest, opts ...grpc.CallOption) (*ArtistSearchResponse, error)
	// === Album Methods ===
	// Get a specific album by ID.
	AlbumGet(ctx context.Context, in *AlbumGetRequest, opts ...grpc.CallOption) (*AlbumGetResponse, error)
	// Search for albums by name.
	AlbumSearch(ctx context.Context, in *AlbumSearchRequest, opts ...grpc.CallOption) (*AlbumSearchResponse, error)
	// === Track Methods ===
	// Get a specific track by ID.
	TrackGet(ctx context.Context, in *TrackGetRequest, opts ...grpc.CallOption) (*TrackGetResponse, error)
	// Search for tracks by name.
	TrackSearch(ctx context.Context, in *TrackSearchRequest, opts ...grpc.CallOption) (*TrackSearchResponse, error)
}

type flixurPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewFlixurPluginClient(cc grpc.ClientConnInterface) FlixurPluginClient {
	return &flixurPluginClient{cc}
}

func (c *flixurPluginClient) GetPluginInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, FlixurPlugin_GetPluginInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flixurPluginClient) ArtistGet(ctx context.Context, in *ArtistGetRequest, opts ...grpc.CallOption) (*ArtistGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtistGetResponse)
	err := c.cc.Invoke(ctx, FlixurPlugin_ArtistGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flixurPluginClient) ArtistSearch(ctx context.Context, in *ArtistSearchRequest, opts ...grpc.CallOption) (*ArtistSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArtistSearchResponse)
	err := c.cc.Invoke(ctx, FlixurPlugin_ArtistSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flixurPluginClient) AlbumGet(ctx context.Context, in *AlbumGetRequest, opts ...grpc.CallOption) (*AlbumGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlbumGetResponse)
	err := c.cc.Invoke(ctx, FlixurPlugin_AlbumGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flixurPluginClient) AlbumSearch(ctx context.Context, in *AlbumSearchRequest, opts ...grpc.CallOption) (*AlbumSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlbumSearchResponse)
	err := c.cc.Invoke(ctx, FlixurPlugin_AlbumSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flixurPluginClient) TrackGet(ctx context.Context, in *TrackGetRequest, opts ...grpc.CallOption) (*TrackGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackGetResponse)
	err := c.cc.Invoke(ctx, FlixurPlugin_TrackGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flixurPluginClient) TrackSearch(ctx context.Context, in *TrackSearchRequest, opts ...grpc.CallOption) (*TrackSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackSearchResponse)
	err := c.cc.Invoke(ctx, FlixurPlugin_TrackSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlixurPluginServer is the server API for FlixurPlugin service.
// All implementations must embed UnimplementedFlixurPluginServer
// for forward compatibility.
//
// The main plugin service. Plugins implement this gRPC service.
type FlixurPluginServer interface {
	// Get plugin metadata and capabilities.
	GetPluginInfo(context.Context, *EmptyRequest) (*PluginInfo, error)
	// === Artist Methods ===
	// Get a specific artist by ID.
	ArtistGet(context.Context, *ArtistGetRequest) (*ArtistGetResponse, error)
	// Search for artists by name.
	ArtistSearch(context.Context, *ArtistSearchRequest) (*ArtistSearchResponse, error)
	// === Album Methods ===
	// Get a specific album by ID.
	AlbumGet(context.Context, *AlbumGetRequest) (*AlbumGetResponse, error)
	// Search for albums by name.
	AlbumSearch(context.Context, *AlbumSearchRequest) (*AlbumSearchResponse, error)
	// === Track Methods ===
	// Get a specific track by ID.
	TrackGet(context.Context, *TrackGetRequest) (*TrackGetResponse, error)
	// Search for tracks by name.
	TrackSearch(context.Context, *TrackSearchRequest) (*TrackSearchResponse, error)
	mustEmbedUnimplementedFlixurPluginServer()
}

// UnimplementedFlixurPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlixurPluginServer struct{}

func (UnimplementedFlixurPluginServer) GetPluginInfo(context.Context, *EmptyRequest) (*PluginInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginInfo not implemented")
}
func (UnimplementedFlixurPluginServer) ArtistGet(context.Context, *ArtistGetRequest) (*ArtistGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArtistGet not implemented")
}
func (UnimplementedFlixurPluginServer) ArtistSearch(context.Context, *ArtistSearchRequest) (*ArtistSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArtistSearch not implemented")
}
func (UnimplementedFlixurPluginServer) AlbumGet(context.Context, *AlbumGetRequest) (*AlbumGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlbumGet not implemented")
}
func (UnimplementedFlixurPluginServer) AlbumSearch(context.Context, *AlbumSearchRequest) (*AlbumSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlbumSearch not implemented")
}
func (UnimplementedFlixurPluginServer) TrackGet(context.Context, *TrackGetRequest) (*TrackGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackGet not implemented")
}
func (UnimplementedFlixurPluginServer) TrackSearch(context.Context, *TrackSearchRequest) (*TrackSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackSearch not implemented")
}
func (UnimplementedFlixurPluginServer) mustEmbedUnimplementedFlixurPluginServer() {}
func (UnimplementedFlixurPluginServer) testEmbeddedByValue()                      {}

// UnsafeFlixurPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlixurPluginServer will
// result in compilation errors.
type UnsafeFlixurPluginServer interface {
	mustEmbedUnimplementedFlixurPluginServer()
}

func RegisterFlixurPluginServer(s grpc.ServiceRegistrar, srv FlixurPluginServer) {
	// If the following call pancis, it indicates UnimplementedFlixurPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlixurPlugin_ServiceDesc, srv)
}

func _FlixurPlugin_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlixurPluginServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlixurPlugin_GetPluginInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlixurPluginServer).GetPluginInfo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlixurPlugin_ArtistGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtistGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlixurPluginServer).ArtistGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlixurPlugin_ArtistGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlixurPluginServer).ArtistGet(ctx, req.(*ArtistGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlixurPlugin_ArtistSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtistSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlixurPluginServer).ArtistSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlixurPlugin_ArtistSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlixurPluginServer).ArtistSearch(ctx, req.(*ArtistSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlixurPlugin_AlbumGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlbumGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlixurPluginServer).AlbumGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlixurPlugin_AlbumGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlixurPluginServer).AlbumGet(ctx, req.(*AlbumGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlixurPlugin_AlbumSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlbumSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlixurPluginServer).AlbumSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlixurPlugin_AlbumSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlixurPluginServer).AlbumSearch(ctx, req.(*AlbumSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlixurPlugin_TrackGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlixurPluginServer).TrackGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlixurPlugin_TrackGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlixurPluginServer).TrackGet(ctx, req.(*TrackGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlixurPlugin_TrackSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlixurPluginServer).TrackSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlixurPlugin_TrackSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlixurPluginServer).TrackSearch(ctx, req.(*TrackSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlixurPlugin_ServiceDesc is the grpc.ServiceDesc for FlixurPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlixurPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flixur.plugins.FlixurPlugin",
	HandlerType: (*FlixurPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPluginInfo",
			Handler:    _FlixurPlugin_GetPluginInfo_Handler,
		},
		{
			MethodName: "ArtistGet",
			Handler:    _FlixurPlugin_ArtistGet_Handler,
		},
		{
			MethodName: "ArtistSearch",
			Handler:    _FlixurPlugin_ArtistSearch_Handler,
		},
		{
			MethodName: "AlbumGet",
			Handler:    _FlixurPlugin_AlbumGet_Handler,
		},
		{
			MethodName: "AlbumSearch",
			Handler:    _FlixurPlugin_AlbumSearch_Handler,
		},
		{
			MethodName: "TrackGet",
			Handler:    _FlixurPlugin_TrackGet_Handler,
		},
		{
			MethodName: "TrackSearch",
			Handler:    _FlixurPlugin_TrackSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugins.proto",
}
