[package]
name = "flixur-protocol"
version = "0.0.1"
edition = "2024"
publish = false

[build-dependencies]
pilota-build = "0.11.31"

[dependencies]
pilota = "0.11.10"
serde = { version = "1.0.218", features = ["derive"] }
