// Code generated by tygo. DO NOT EDIT.

//////////
// source: music.pb.go

export type AlbumType = number /* int32 */;
export const AlbumType_SINGLE: AlbumType = 0;
export const AlbumType_ALBUM: AlbumType = 1;
export type TrackExplicitness = number /* int32 */;
/**
 * Normal
 */
export const TrackExplicitness_CLEAN: TrackExplicitness = 0;
/**
 * Explicit
 */
export const TrackExplicitness_EXPLICIT: TrackExplicitness = 1;
/**
 * Rated X
 */
export const TrackExplicitness_RESTRICTED: TrackExplicitness = 2;
/**
 * Usually an artist returned from a provider.
 */
export interface Artist {
  /**
   * ID of the artist from the provider.
   */
  id: string;
  /**
   * ID of the plugin that provided this artist.
   */
  provider: string;
  /**
   * Name of the artist.
   */
  name: string;
  /**
   * Icon URL for the artist. Should be accessible via HTTP with CORS.
   */
  icon?: string;
  /**
   * Description of the artist.
   */
  description?: string;
  /**
   * Geographical location of the artist.
   */
  location?: string;
  /**
   * Follower count for the artist. (using the platform of choice)
   */
  followers?: number /* int64 */;
}
/**
 * An artist stored locally.
 */
export interface LocalArtist {
  /**
   * Unique ID for the artist. (unique across providers)
   */
  id: string;
  /**
   * Base metadata for the artist.
   */
  metadata?: Artist;
  /**
   * Rating for the artist.
   */
  rating?: number /* int32 */;
}
export interface Album {
  /**
   * Unique ID for the album.
   */
  id: string;
  /**
   * IDs of artists on this album.
   */
  artists: string[];
  /**
   * Name of the album.
   */
  name: string;
  /**
   * Cover URL for album art. Should be accessible via HTTP with CORS.
   */
  icon?: string;
  /**
   * Unix timestamp the album was released. (in seconds)
   */
  date: number /* int64 */;
  /**
   * Type of the album.
   */
  type: AlbumType;
  /**
   * Rating for the track.
   */
  rating?: number /* int32 */;
  /**
   * Description of the album.
   */
  description?: string;
  /**
   * List of genres for the album.
   */
  genres: string[];
}
export interface Track {
  /**
   * Unique ID for the track.
   */
  id: string;
  /**
   * Unique ISRC of the track. May be unofficial.
   */
  isrc: string;
  /**
   * IDs of artists on this track.
   */
  artists: string[];
  /**
   * Title of the track.
   */
  title: string;
  /**
   * Track number in the album.
   */
  index: number /* int32 */;
  /**
   * Duration in ms of the track.
   */
  duration: number /* int64 */;
  /**
   * Rating for the track.
   */
  rating?: number /* int32 */;
  /**
   * The explicitness of the track.
   */
  explicitness: TrackExplicitness;
}

//////////
// source: music_features.pb.go

/**
 * GetArtist
 */
export interface ArtistGetRequest {
  id: string;
}
export interface ArtistGetResponse {
  artist?: Artist;
}
/**
 * SearchArtists
 */
export interface ArtistSearchRequest {
  query: string;
  /**
   * Limit of items to fetch. Will be clamped to max request size limit if applicable.
   */
  limit: number /* int32 */;
}
export interface ArtistSearchResponse {
  results?: (Artist | undefined)[];
}
/**
 * GetAlbum
 */
export interface AlbumGetRequest {
  id: string;
}
export interface AlbumGetResponse {
  album?: Album;
}
/**
 * SearchAlbums
 */
export interface AlbumSearchRequest {
  query: string;
  /**
   * Limit of items to fetch. Will be clamped to max request size limit if applicable.
   */
  limit: number /* int32 */;
}
export interface AlbumSearchResponse {
  results?: (Album | undefined)[];
}
/**
 * GetTrack
 */
export interface TrackGetRequest {
  id: string;
}
export interface TrackGetResponse {
  track?: Track;
}
/**
 * SearchTracks
 */
export interface TrackSearchRequest {
  query: string;
  /**
   * Limit of items to fetch. Will be clamped to max request size limit if applicable.
   */
  limit: number /* int32 */;
}
export interface TrackSearchResponse {
  results?: (Track | undefined)[];
}

//////////
// source: plugins.pb.go

/**
 * Used to test if a plugin supports certain features.
 */
export type Feature = number /* int32 */;
/**
 * Implements `Artist*`, `Album*`, `Track*` RPC calls
 */
export const Feature_MUSIC_METADATA: Feature = 0;
/**
 * Empty message for RPC calls that don't require input.
 */
export interface EmptyRequest {
}
/**
 * Plugin metadata returned by GetPluginInfo.
 */
export interface PluginInfo {
  /**
   * Unique Plugin ID.
   */
  id: string;
  /**
   * Name of the plugin.
   */
  name: string;
  /**
   * Numerical version of the plugin.
   */
  version: number /* int32 */;
  /**
   * List of plugin IDs that should be loaded before this plugin.
   */
  dependencies: string[];
  /**
   * List of feature names this plugin implements.
   */
  features: Feature[];
  /**
   * Should be the full identifier of an Iconify icon for this plugin. (https://icon-sets.iconify.design)
   */
  icon: string;
  /**
   * Short description of the plugin.
   */
  description: string;
  /**
   * Name of the plugin author.
   */
  author: string;
  /**
   * Direct link to the source code of the plugin.
   */
  url: string;
}

//////////
// source: plugins_grpc.pb.go

export const FlixurPlugin_GetPluginInfo_FullMethodName = "/flixur.plugins.FlixurPlugin/GetPluginInfo";
export const FlixurPlugin_ArtistGet_FullMethodName = "/flixur.plugins.FlixurPlugin/ArtistGet";
export const FlixurPlugin_ArtistSearch_FullMethodName = "/flixur.plugins.FlixurPlugin/ArtistSearch";
export const FlixurPlugin_AlbumGet_FullMethodName = "/flixur.plugins.FlixurPlugin/AlbumGet";
export const FlixurPlugin_AlbumSearch_FullMethodName = "/flixur.plugins.FlixurPlugin/AlbumSearch";
export const FlixurPlugin_TrackGet_FullMethodName = "/flixur.plugins.FlixurPlugin/TrackGet";
export const FlixurPlugin_TrackSearch_FullMethodName = "/flixur.plugins.FlixurPlugin/TrackSearch";
/**
 * FlixurPluginClient is the client API for FlixurPlugin service.
 * For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
 * The main plugin service. Plugins implement this gRPC service.
 */
export type FlixurPluginClient = any;
/**
 * FlixurPluginServer is the server API for FlixurPlugin service.
 * All implementations must embed UnimplementedFlixurPluginServer
 * for forward compatibility.
 * The main plugin service. Plugins implement this gRPC service.
 */
export type FlixurPluginServer = any;
/**
 * UnimplementedFlixurPluginServer must be embedded to have
 * forward compatible implementations.
 * NOTE: this should be embedded by value instead of pointer to avoid a nil
 * pointer dereference when methods are called.
 */
export interface UnimplementedFlixurPluginServer {
}
/**
 * UnsafeFlixurPluginServer may be embedded to opt out of forward compatibility for this service.
 * Use of this interface is not recommended, as added methods to FlixurPluginServer will
 * result in compilation errors.
 */
export type UnsafeFlixurPluginServer = any;
