// Code generated by tygo. DO NOT EDIT.

//////////
// source: features.pb.go

export type FeatureErrorCode = number /* int32 */;
export const FeatureErrorCode_UNKNOWN: FeatureErrorCode = 0;
export const FeatureErrorCode_NOT_INITIALIZED: FeatureErrorCode = 1;
export const FeatureErrorCode_NOT_FOUND: FeatureErrorCode = 2;
export const FeatureErrorCode_RATELIMITED: FeatureErrorCode = 3;
/**
 * Error response from any feature.
 */
export interface FeatureError {
  code: number /* int32 */;
  message: string;
}
/**
 * Get a specific artist by ID.
 */
export interface FeatureArtistGetRequest {
  id: string;
}
export interface FeatureArtistGetResponse {
  artist?: Artist;
}
/**
 * Search for an artist by name.
 */
export interface FeatureArtistSearchRequest {
  query: string;
  /**
   * Limit of items to fetch. Will be clamped to max request size limit if applicable.
   */
  limit: number /* int32 */;
}
export interface FeatureArtistSearchResponse {
  results?: (Artist | undefined)[];
}

//////////
// source: music.pb.go

export type AlbumType = number /* int32 */;
export const AlbumType_SINGLE: AlbumType = 0;
export const AlbumType_ALBUM: AlbumType = 1;
export type TrackExplicitness = number /* int32 */;
/**
 * Normal
 */
export const TrackExplicitness_CLEAN: TrackExplicitness = 0;
/**
 * Explicit
 */
export const TrackExplicitness_EXPLICIT: TrackExplicitness = 1;
/**
 * Rated X
 */
export const TrackExplicitness_RESTRICTED: TrackExplicitness = 2;
/**
 * Usually an artist returned from a provider.
 */
export interface Artist {
  /**
   * ID of the artist from the provider.
   */
  id: string;
  /**
   * ID of the plugin that provided this artist.
   */
  provider: string;
  /**
   * Name of the artist.
   */
  name: string;
  /**
   * Icon URL for the artist. Should be accessible via HTTP with CORS.
   */
  icon?: string;
  /**
   * Description of the artist.
   */
  description?: string;
  /**
   * Geographical location of the artist.
   */
  location?: string;
  /**
   * Follower count for the artist. (using the platform of choice)
   */
  followers?: number /* int64 */;
}
/**
 * An artist stored locally.
 */
export interface LocalArtist {
  /**
   * Unique ID for the artist. (unique across providers)
   */
  id: string;
  /**
   * Base metadata for the artist.
   */
  metadata?: Artist;
  /**
   * Rating for the artist.
   */
  rating?: number /* int32 */;
}
export interface Album {
  /**
   * Unique ID for the album.
   */
  id: string;
  /**
   * IDs of artists on this album.
   */
  artists: string[];
  /**
   * Name of the album.
   */
  name: string;
  /**
   * Cover URL for album art. Should be accessible via HTTP with CORS.
   */
  icon?: string;
  /**
   * Unix timestamp the album was released. (in seconds)
   */
  date: number /* int64 */;
  /**
   * Type of the album.
   */
  type: AlbumType;
  /**
   * Rating for the track.
   */
  rating?: number /* int32 */;
  /**
   * Description of the album.
   */
  description?: string;
  /**
   * List of genres for the album.
   */
  genres: string[];
}
export interface Track {
  /**
   * Unique ID for the track.
   */
  id: string;
  /**
   * Unique ISRC of the track. May be unofficial.
   */
  isrc: string;
  /**
   * IDs of artists on this track.
   */
  artists: string[];
  /**
   * Title of the track.
   */
  title: string;
  /**
   * Track number in the album.
   */
  index: number /* int32 */;
  /**
   * Duration in ms of the track.
   */
  duration: number /* int64 */;
  /**
   * Rating for the track.
   */
  rating?: number /* int32 */;
  /**
   * The explicitness of the track.
   */
  explicitness: TrackExplicitness;
}

//////////
// source: plugins.pb.go

export type PacketType = number /* int32 */;
export const PacketType_INIT: PacketType = 0; // PacketInit
export const PacketType_INFO: PacketType = 1; // PacketInfo
export const PacketType_FEATURE_REQUEST: PacketType = 2; // PacketFeatureRequest
export const PacketType_FEATURE_RESPONSE: PacketType = 3; // PacketFeatureResponse
export const PacketType_DESTROY: PacketType = 4; // PacketDestroy
/**
 * Functions that plugins can implement.
 */
export type Features = number /* int32 */;
/**
 * Get a specific artist by internal ID.
 */
export const Features_ARTIST_GET: Features = 0;
/**
 * Search for an artist by name.
 */
export const Features_ARTIST_SEARCH: Features = 1;
/**
 * Get a specific album by internal ID.
 */
export const Features_ALBUM_GET: Features = 2;
/**
 * Search for an album by name.
 */
export const Features_ALBUM_SEARCH: Features = 3;
/**
 * Get a specific track by internal ID.
 */
export const Features_TRACK_GET: Features = 4;
/**
 * Search for a track by name.
 */
export const Features_TRACK_SEARCH: Features = 5;
/**
 * Packets sent between server and plugin.
 */
export interface PluginPacket {
  /**
   * Type of the packet.
   */
  type: PacketType;
  /**
   * Identifier for the packet. (used to respond to certain requests)
   */
  id: string;
  /**
   * The actual packet data. (a below protobuf)
   */
  data: string;
}
/**
 * Sent by the server to tell a plugin to initialize.
 */
export interface PacketInit {
  /**
   * Current numerical version of the server.
   */
  version: number /* int32 */;
}
/**
 * Sent by a plugin to identify itself.
 */
export interface PacketInfo {
  /**
   * Unique Plugin ID.
   */
  id: string;
  /**
   * Numerical version of the plugin.
   */
  version: number /* int32 */;
  /**
   * Minimum required app version for the plugin to load.
   */
  min_version: number /* int32 */;
  /**
   * List of plugin IDs that should be loaded before this plugin.
   */
  dependencies: string[];
  /**
   * List of features this plugin implements.
   */
  features: Features[];
  /**
   * Name of the plugin.
   */
  name: string;
  /**
   * Should be the full identifier of an Iconify icon for this plugin. (https://icon-sets.iconify.design)
   */
  icon: string;
  /**
   * Short description of the plugin.
   */
  description: string;
  /**
   * Name of the plugin author.
   */
  author: string;
  /**
   * Direct link to the source code of the plugin.
   */
  url: string;
}
/**
 * Calls a feature implemented by the plugin.
 */
export interface PacketFeatureRequest {
  /**
   * Name of the feature to call.
   */
  feature: Features;
  /**
   * Request payload from `features` to use.
   */
  payload: string;
}
/**
 * Response from a feature request.
 */
export interface PacketFeatureResponse {
  /**
   * Name of the feature that created the response.
   */
  feature: Features;
  /**
   * Response payload from `features` matching the feature.
   */
  payload: string;
  /**
   * Optional error response from the request.
   */
  error?: FeatureError;
}
/**
 * Used when the server is shutting down or plugin is being uninstalled.
 */
export interface PacketDestroy {
}
