/**
 * Generated by @openapi-codegen
 *
 * @version 0.0.1
 */
import type * as Fetcher from "./flixurFetcher";
import { flixurFetch } from "./flixurFetcher";
import type * as Schemas from "./flixurSchemas";

export type GetGreetingByNamePathParams = {
  /**
   * Name to greet
   *
   * @example world
   * @maxLength 30
   */
  name: string;
};

export type GetGreetingByNameError = Fetcher.ErrorWrapper<undefined>;

export type GetGreetingByNameVariables = {
  pathParams: GetGreetingByNamePathParams;
};

export const getGreetingByName = (variables: GetGreetingByNameVariables, signal?: AbortSignal) =>
  flixurFetch<
    Schemas.GreetingOutputBody,
    GetGreetingByNameError,
    undefined,
    {},
    {},
    GetGreetingByNamePathParams
  >({ url: "/greeting/{name}", method: "get", ...variables, signal });
