/**
 * Generated by @openapi-codegen
 *
 * @version 0.0.1
 */
export type Artist = {
  description?: string;
  /**
   * @format int64
   */
  followers?: number;
  icon?: string;
  id: string;
  internalID: string;
  location?: string;
  name: string;
  provider: string;
  /**
   * @format int32
   */
  rating?: number;
};

export type ArtistSearchRequest = {
  /**
   * A URL to the JSON Schema for this object.
   *
   * @example /api/schemas/Artist-searchRequest.json
   * @format uri
   */
  $schema?: string;
  /**
   * @default 10
   * @example 100
   * @format int64
   * @maximum 100
   * @minimum 1
   */
  limit: number;
  /**
   * Plugin ID to use for the request. Omit to use the local server.
   */
  plugin?: string;
  /**
   * @example Jerry Springer
   * @maxLength 250
   * @minLength 1
   */
  query: string;
};

export type ArtistSearchOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   *
   * @example /api/schemas/ArtistSearchOutputBody.json
   * @format uri
   */
  $schema?: string;
  list: Artist[];
};

export type ErrorDetail = {
  /**
   * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
   */
  location?: string;
  /**
   * Error message text
   */
  message?: string;
  /**
   * The value at the given location
   */
  value?: void;
};

export type ErrorModel = {
  /**
   * A URL to the JSON Schema for this object.
   *
   * @example /api/schemas/ErrorModel.json
   * @format uri
   */
  $schema?: string;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   *
   * @example Property foo is required but is missing.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: ErrorDetail[];
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   *
   * @example https://example.com/error-log/abc123
   * @format uri
   */
  instance?: string;
  /**
   * HTTP status code
   *
   * @example 400
   * @format int64
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   *
   * @example Bad Request
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   *
   * @default about:blank
   * @example https://example.com/errors/example
   * @format uri
   */
  type?: string;
};

export type GreetingOutputBody = {
  /**
   * A URL to the JSON Schema for this object.
   *
   * @example /api/schemas/GreetingOutputBody.json
   * @format uri
   */
  $schema?: string;
  /**
   * Greeting message
   *
   * @example Hello, world!
   */
  message: string;
};
